// SPDX-License-Identifier: Apache-2.0

// Public schema for the investigation engine: the investigation service, the hypothesis
// ledger, the typed query algebra, the digest contract (shared with features 003 and 005),
// the recording format and the fixture ground truth. Served via ConnectRPC alongside
// sreagent.graph.v1. Versioned with buf; breaking changes require a MAJOR bump
// (constitution IX). This package is the published home of the algebra, the digest, the
// coverage block, the join keys, the drill-down handles and the typed outcomes: a telemetry
// backend (005 "Dependencies on 001") implements these messages, it does not define its own.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sreagent/investigation/v1/investigation.proto

package investigationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Pierre-Theophile/aisre/api/sreagent/investigation/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TelemetryBackendServiceName is the fully-qualified name of the TelemetryBackendService service.
	TelemetryBackendServiceName = "sreagent.investigation.v1.TelemetryBackendService"
	// InvestigationServiceName is the fully-qualified name of the InvestigationService service.
	InvestigationServiceName = "sreagent.investigation.v1.InvestigationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TelemetryBackendServiceDescribeProcedure is the fully-qualified name of the
	// TelemetryBackendService's Describe RPC.
	TelemetryBackendServiceDescribeProcedure = "/sreagent.investigation.v1.TelemetryBackendService/Describe"
	// TelemetryBackendServiceExecuteProcedure is the fully-qualified name of the
	// TelemetryBackendService's Execute RPC.
	TelemetryBackendServiceExecuteProcedure = "/sreagent.investigation.v1.TelemetryBackendService/Execute"
	// InvestigationServiceInvestigateProcedure is the fully-qualified name of the
	// InvestigationService's Investigate RPC.
	InvestigationServiceInvestigateProcedure = "/sreagent.investigation.v1.InvestigationService/Investigate"
	// InvestigationServiceDeclareProcedure is the fully-qualified name of the InvestigationService's
	// Declare RPC.
	InvestigationServiceDeclareProcedure = "/sreagent.investigation.v1.InvestigationService/Declare"
	// InvestigationServiceGetProcedure is the fully-qualified name of the InvestigationService's Get
	// RPC.
	InvestigationServiceGetProcedure = "/sreagent.investigation.v1.InvestigationService/Get"
	// InvestigationServiceReplayProcedure is the fully-qualified name of the InvestigationService's
	// Replay RPC.
	InvestigationServiceReplayProcedure = "/sreagent.investigation.v1.InvestigationService/Replay"
	// InvestigationServiceReopenProcedure is the fully-qualified name of the InvestigationService's
	// Reopen RPC.
	InvestigationServiceReopenProcedure = "/sreagent.investigation.v1.InvestigationService/Reopen"
	// InvestigationServiceSubmitHumanFactProcedure is the fully-qualified name of the
	// InvestigationService's SubmitHumanFact RPC.
	InvestigationServiceSubmitHumanFactProcedure = "/sreagent.investigation.v1.InvestigationService/SubmitHumanFact"
	// InvestigationServiceReviewProcedure is the fully-qualified name of the InvestigationService's
	// Review RPC.
	InvestigationServiceReviewProcedure = "/sreagent.investigation.v1.InvestigationService/Review"
	// InvestigationServiceLabelProcedure is the fully-qualified name of the InvestigationService's
	// Label RPC.
	InvestigationServiceLabelProcedure = "/sreagent.investigation.v1.InvestigationService/Label"
	// InvestigationServiceListProcedure is the fully-qualified name of the InvestigationService's List
	// RPC.
	InvestigationServiceListProcedure = "/sreagent.investigation.v1.InvestigationService/List"
	// InvestigationServiceExportProcedure is the fully-qualified name of the InvestigationService's
	// Export RPC.
	InvestigationServiceExportProcedure = "/sreagent.investigation.v1.InvestigationService/Export"
)

// TelemetryBackendServiceClient is a client for the
// sreagent.investigation.v1.TelemetryBackendService service.
type TelemetryBackendServiceClient interface {
	Describe(context.Context, *connect.Request[v1.DescribeBackendRequest]) (*connect.Response[v1.BackendDescription], error)
	Execute(context.Context, *connect.Request[v1.AlgebraRequest]) (*connect.Response[v1.AlgebraResponse], error)
}

// NewTelemetryBackendServiceClient constructs a client for the
// sreagent.investigation.v1.TelemetryBackendService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTelemetryBackendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TelemetryBackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	telemetryBackendServiceMethods := v1.File_sreagent_investigation_v1_investigation_proto.Services().ByName("TelemetryBackendService").Methods()
	return &telemetryBackendServiceClient{
		describe: connect.NewClient[v1.DescribeBackendRequest, v1.BackendDescription](
			httpClient,
			baseURL+TelemetryBackendServiceDescribeProcedure,
			connect.WithSchema(telemetryBackendServiceMethods.ByName("Describe")),
			connect.WithClientOptions(opts...),
		),
		execute: connect.NewClient[v1.AlgebraRequest, v1.AlgebraResponse](
			httpClient,
			baseURL+TelemetryBackendServiceExecuteProcedure,
			connect.WithSchema(telemetryBackendServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
	}
}

// telemetryBackendServiceClient implements TelemetryBackendServiceClient.
type telemetryBackendServiceClient struct {
	describe *connect.Client[v1.DescribeBackendRequest, v1.BackendDescription]
	execute  *connect.Client[v1.AlgebraRequest, v1.AlgebraResponse]
}

// Describe calls sreagent.investigation.v1.TelemetryBackendService.Describe.
func (c *telemetryBackendServiceClient) Describe(ctx context.Context, req *connect.Request[v1.DescribeBackendRequest]) (*connect.Response[v1.BackendDescription], error) {
	return c.describe.CallUnary(ctx, req)
}

// Execute calls sreagent.investigation.v1.TelemetryBackendService.Execute.
func (c *telemetryBackendServiceClient) Execute(ctx context.Context, req *connect.Request[v1.AlgebraRequest]) (*connect.Response[v1.AlgebraResponse], error) {
	return c.execute.CallUnary(ctx, req)
}

// TelemetryBackendServiceHandler is an implementation of the
// sreagent.investigation.v1.TelemetryBackendService service.
type TelemetryBackendServiceHandler interface {
	Describe(context.Context, *connect.Request[v1.DescribeBackendRequest]) (*connect.Response[v1.BackendDescription], error)
	Execute(context.Context, *connect.Request[v1.AlgebraRequest]) (*connect.Response[v1.AlgebraResponse], error)
}

// NewTelemetryBackendServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTelemetryBackendServiceHandler(svc TelemetryBackendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	telemetryBackendServiceMethods := v1.File_sreagent_investigation_v1_investigation_proto.Services().ByName("TelemetryBackendService").Methods()
	telemetryBackendServiceDescribeHandler := connect.NewUnaryHandler(
		TelemetryBackendServiceDescribeProcedure,
		svc.Describe,
		connect.WithSchema(telemetryBackendServiceMethods.ByName("Describe")),
		connect.WithHandlerOptions(opts...),
	)
	telemetryBackendServiceExecuteHandler := connect.NewUnaryHandler(
		TelemetryBackendServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(telemetryBackendServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sreagent.investigation.v1.TelemetryBackendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TelemetryBackendServiceDescribeProcedure:
			telemetryBackendServiceDescribeHandler.ServeHTTP(w, r)
		case TelemetryBackendServiceExecuteProcedure:
			telemetryBackendServiceExecuteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTelemetryBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTelemetryBackendServiceHandler struct{}

func (UnimplementedTelemetryBackendServiceHandler) Describe(context.Context, *connect.Request[v1.DescribeBackendRequest]) (*connect.Response[v1.BackendDescription], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.TelemetryBackendService.Describe is not implemented"))
}

func (UnimplementedTelemetryBackendServiceHandler) Execute(context.Context, *connect.Request[v1.AlgebraRequest]) (*connect.Response[v1.AlgebraResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.TelemetryBackendService.Execute is not implemented"))
}

// InvestigationServiceClient is a client for the sreagent.investigation.v1.InvestigationService
// service.
type InvestigationServiceClient interface {
	Investigate(context.Context, *connect.Request[v1.InvestigateRequest]) (*connect.ServerStreamForClient[v1.Investigation], error)
	// A declared incident is a first-class intake, not a special case (FR-001a). Re-delivery under
	// a seen idempotency key is a no-op returning the existing investigation (FR-008b).
	Declare(context.Context, *connect.Request[v1.DeclareRequest]) (*connect.ServerStreamForClient[v1.Investigation], error)
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.Investigation], error)
	Replay(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	Reopen(context.Context, *connect.Request[v1.ReopenRequest]) (*connect.Response[v1.Investigation], error)
	SubmitHumanFact(context.Context, *connect.Request[v1.SubmitHumanFactRequest]) (*connect.Response[v1.Investigation], error)
	Review(context.Context, *connect.Request[v1.ReviewRequest]) (*connect.Response[v1.Investigation], error)
	Label(context.Context, *connect.Request[v1.LabelRequest]) (*connect.Response[v1.Investigation], error)
	// FR-064's dual surface: every command in the dual-surface subset has an RPC.
	List(context.Context, *connect.Request[v1.ListInvestigationsRequest]) (*connect.Response[v1.ListInvestigationsResponse], error)
	Export(context.Context, *connect.Request[v1.ExportRequest]) (*connect.Response[v1.ExportResponse], error)
}

// NewInvestigationServiceClient constructs a client for the
// sreagent.investigation.v1.InvestigationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInvestigationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InvestigationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	investigationServiceMethods := v1.File_sreagent_investigation_v1_investigation_proto.Services().ByName("InvestigationService").Methods()
	return &investigationServiceClient{
		investigate: connect.NewClient[v1.InvestigateRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceInvestigateProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Investigate")),
			connect.WithClientOptions(opts...),
		),
		declare: connect.NewClient[v1.DeclareRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceDeclareProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Declare")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceGetProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		replay: connect.NewClient[v1.ReplayRequest, v1.ReplayResponse](
			httpClient,
			baseURL+InvestigationServiceReplayProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Replay")),
			connect.WithClientOptions(opts...),
		),
		reopen: connect.NewClient[v1.ReopenRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceReopenProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Reopen")),
			connect.WithClientOptions(opts...),
		),
		submitHumanFact: connect.NewClient[v1.SubmitHumanFactRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceSubmitHumanFactProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("SubmitHumanFact")),
			connect.WithClientOptions(opts...),
		),
		review: connect.NewClient[v1.ReviewRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceReviewProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Review")),
			connect.WithClientOptions(opts...),
		),
		label: connect.NewClient[v1.LabelRequest, v1.Investigation](
			httpClient,
			baseURL+InvestigationServiceLabelProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Label")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListInvestigationsRequest, v1.ListInvestigationsResponse](
			httpClient,
			baseURL+InvestigationServiceListProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		export: connect.NewClient[v1.ExportRequest, v1.ExportResponse](
			httpClient,
			baseURL+InvestigationServiceExportProcedure,
			connect.WithSchema(investigationServiceMethods.ByName("Export")),
			connect.WithClientOptions(opts...),
		),
	}
}

// investigationServiceClient implements InvestigationServiceClient.
type investigationServiceClient struct {
	investigate     *connect.Client[v1.InvestigateRequest, v1.Investigation]
	declare         *connect.Client[v1.DeclareRequest, v1.Investigation]
	get             *connect.Client[v1.GetRequest, v1.Investigation]
	replay          *connect.Client[v1.ReplayRequest, v1.ReplayResponse]
	reopen          *connect.Client[v1.ReopenRequest, v1.Investigation]
	submitHumanFact *connect.Client[v1.SubmitHumanFactRequest, v1.Investigation]
	review          *connect.Client[v1.ReviewRequest, v1.Investigation]
	label           *connect.Client[v1.LabelRequest, v1.Investigation]
	list            *connect.Client[v1.ListInvestigationsRequest, v1.ListInvestigationsResponse]
	export          *connect.Client[v1.ExportRequest, v1.ExportResponse]
}

// Investigate calls sreagent.investigation.v1.InvestigationService.Investigate.
func (c *investigationServiceClient) Investigate(ctx context.Context, req *connect.Request[v1.InvestigateRequest]) (*connect.ServerStreamForClient[v1.Investigation], error) {
	return c.investigate.CallServerStream(ctx, req)
}

// Declare calls sreagent.investigation.v1.InvestigationService.Declare.
func (c *investigationServiceClient) Declare(ctx context.Context, req *connect.Request[v1.DeclareRequest]) (*connect.ServerStreamForClient[v1.Investigation], error) {
	return c.declare.CallServerStream(ctx, req)
}

// Get calls sreagent.investigation.v1.InvestigationService.Get.
func (c *investigationServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.Investigation], error) {
	return c.get.CallUnary(ctx, req)
}

// Replay calls sreagent.investigation.v1.InvestigationService.Replay.
func (c *investigationServiceClient) Replay(ctx context.Context, req *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return c.replay.CallUnary(ctx, req)
}

// Reopen calls sreagent.investigation.v1.InvestigationService.Reopen.
func (c *investigationServiceClient) Reopen(ctx context.Context, req *connect.Request[v1.ReopenRequest]) (*connect.Response[v1.Investigation], error) {
	return c.reopen.CallUnary(ctx, req)
}

// SubmitHumanFact calls sreagent.investigation.v1.InvestigationService.SubmitHumanFact.
func (c *investigationServiceClient) SubmitHumanFact(ctx context.Context, req *connect.Request[v1.SubmitHumanFactRequest]) (*connect.Response[v1.Investigation], error) {
	return c.submitHumanFact.CallUnary(ctx, req)
}

// Review calls sreagent.investigation.v1.InvestigationService.Review.
func (c *investigationServiceClient) Review(ctx context.Context, req *connect.Request[v1.ReviewRequest]) (*connect.Response[v1.Investigation], error) {
	return c.review.CallUnary(ctx, req)
}

// Label calls sreagent.investigation.v1.InvestigationService.Label.
func (c *investigationServiceClient) Label(ctx context.Context, req *connect.Request[v1.LabelRequest]) (*connect.Response[v1.Investigation], error) {
	return c.label.CallUnary(ctx, req)
}

// List calls sreagent.investigation.v1.InvestigationService.List.
func (c *investigationServiceClient) List(ctx context.Context, req *connect.Request[v1.ListInvestigationsRequest]) (*connect.Response[v1.ListInvestigationsResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Export calls sreagent.investigation.v1.InvestigationService.Export.
func (c *investigationServiceClient) Export(ctx context.Context, req *connect.Request[v1.ExportRequest]) (*connect.Response[v1.ExportResponse], error) {
	return c.export.CallUnary(ctx, req)
}

// InvestigationServiceHandler is an implementation of the
// sreagent.investigation.v1.InvestigationService service.
type InvestigationServiceHandler interface {
	Investigate(context.Context, *connect.Request[v1.InvestigateRequest], *connect.ServerStream[v1.Investigation]) error
	// A declared incident is a first-class intake, not a special case (FR-001a). Re-delivery under
	// a seen idempotency key is a no-op returning the existing investigation (FR-008b).
	Declare(context.Context, *connect.Request[v1.DeclareRequest], *connect.ServerStream[v1.Investigation]) error
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.Investigation], error)
	Replay(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	Reopen(context.Context, *connect.Request[v1.ReopenRequest]) (*connect.Response[v1.Investigation], error)
	SubmitHumanFact(context.Context, *connect.Request[v1.SubmitHumanFactRequest]) (*connect.Response[v1.Investigation], error)
	Review(context.Context, *connect.Request[v1.ReviewRequest]) (*connect.Response[v1.Investigation], error)
	Label(context.Context, *connect.Request[v1.LabelRequest]) (*connect.Response[v1.Investigation], error)
	// FR-064's dual surface: every command in the dual-surface subset has an RPC.
	List(context.Context, *connect.Request[v1.ListInvestigationsRequest]) (*connect.Response[v1.ListInvestigationsResponse], error)
	Export(context.Context, *connect.Request[v1.ExportRequest]) (*connect.Response[v1.ExportResponse], error)
}

// NewInvestigationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInvestigationServiceHandler(svc InvestigationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	investigationServiceMethods := v1.File_sreagent_investigation_v1_investigation_proto.Services().ByName("InvestigationService").Methods()
	investigationServiceInvestigateHandler := connect.NewServerStreamHandler(
		InvestigationServiceInvestigateProcedure,
		svc.Investigate,
		connect.WithSchema(investigationServiceMethods.ByName("Investigate")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceDeclareHandler := connect.NewServerStreamHandler(
		InvestigationServiceDeclareProcedure,
		svc.Declare,
		connect.WithSchema(investigationServiceMethods.ByName("Declare")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceGetHandler := connect.NewUnaryHandler(
		InvestigationServiceGetProcedure,
		svc.Get,
		connect.WithSchema(investigationServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceReplayHandler := connect.NewUnaryHandler(
		InvestigationServiceReplayProcedure,
		svc.Replay,
		connect.WithSchema(investigationServiceMethods.ByName("Replay")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceReopenHandler := connect.NewUnaryHandler(
		InvestigationServiceReopenProcedure,
		svc.Reopen,
		connect.WithSchema(investigationServiceMethods.ByName("Reopen")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceSubmitHumanFactHandler := connect.NewUnaryHandler(
		InvestigationServiceSubmitHumanFactProcedure,
		svc.SubmitHumanFact,
		connect.WithSchema(investigationServiceMethods.ByName("SubmitHumanFact")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceReviewHandler := connect.NewUnaryHandler(
		InvestigationServiceReviewProcedure,
		svc.Review,
		connect.WithSchema(investigationServiceMethods.ByName("Review")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceLabelHandler := connect.NewUnaryHandler(
		InvestigationServiceLabelProcedure,
		svc.Label,
		connect.WithSchema(investigationServiceMethods.ByName("Label")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceListHandler := connect.NewUnaryHandler(
		InvestigationServiceListProcedure,
		svc.List,
		connect.WithSchema(investigationServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	investigationServiceExportHandler := connect.NewUnaryHandler(
		InvestigationServiceExportProcedure,
		svc.Export,
		connect.WithSchema(investigationServiceMethods.ByName("Export")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sreagent.investigation.v1.InvestigationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InvestigationServiceInvestigateProcedure:
			investigationServiceInvestigateHandler.ServeHTTP(w, r)
		case InvestigationServiceDeclareProcedure:
			investigationServiceDeclareHandler.ServeHTTP(w, r)
		case InvestigationServiceGetProcedure:
			investigationServiceGetHandler.ServeHTTP(w, r)
		case InvestigationServiceReplayProcedure:
			investigationServiceReplayHandler.ServeHTTP(w, r)
		case InvestigationServiceReopenProcedure:
			investigationServiceReopenHandler.ServeHTTP(w, r)
		case InvestigationServiceSubmitHumanFactProcedure:
			investigationServiceSubmitHumanFactHandler.ServeHTTP(w, r)
		case InvestigationServiceReviewProcedure:
			investigationServiceReviewHandler.ServeHTTP(w, r)
		case InvestigationServiceLabelProcedure:
			investigationServiceLabelHandler.ServeHTTP(w, r)
		case InvestigationServiceListProcedure:
			investigationServiceListHandler.ServeHTTP(w, r)
		case InvestigationServiceExportProcedure:
			investigationServiceExportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInvestigationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInvestigationServiceHandler struct{}

func (UnimplementedInvestigationServiceHandler) Investigate(context.Context, *connect.Request[v1.InvestigateRequest], *connect.ServerStream[v1.Investigation]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Investigate is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Declare(context.Context, *connect.Request[v1.DeclareRequest], *connect.ServerStream[v1.Investigation]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Declare is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.Investigation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Get is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Replay(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Replay is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Reopen(context.Context, *connect.Request[v1.ReopenRequest]) (*connect.Response[v1.Investigation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Reopen is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) SubmitHumanFact(context.Context, *connect.Request[v1.SubmitHumanFactRequest]) (*connect.Response[v1.Investigation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.SubmitHumanFact is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Review(context.Context, *connect.Request[v1.ReviewRequest]) (*connect.Response[v1.Investigation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Review is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Label(context.Context, *connect.Request[v1.LabelRequest]) (*connect.Response[v1.Investigation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Label is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) List(context.Context, *connect.Request[v1.ListInvestigationsRequest]) (*connect.Response[v1.ListInvestigationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.List is not implemented"))
}

func (UnimplementedInvestigationServiceHandler) Export(context.Context, *connect.Request[v1.ExportRequest]) (*connect.Response[v1.ExportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.investigation.v1.InvestigationService.Export is not implemented"))
}
