// SPDX-License-Identifier: Apache-2.0

package k8s_test

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	graphv1 "github.com/Pierre-Theophile/aisre/api/sreagent/graph/v1"
	k8sfeeder "github.com/Pierre-Theophile/aisre/internal/feeders/k8s"
	"github.com/Pierre-Theophile/aisre/internal/fixture"
	"github.com/Pierre-Theophile/aisre/internal/graph"
	"github.com/Pierre-Theophile/aisre/internal/projector"
	"github.com/Pierre-Theophile/aisre/internal/store/postgres/pgtest"
	"github.com/Pierre-Theophile/aisre/pkg/feeder"
	"github.com/Pierre-Theophile/aisre/pkg/feeder/emit"
	"github.com/Pierre-Theophile/aisre/pkg/feeder/testkit"
)

// Conformance (T061, US3 scenarios 1–3).
//
// testdata/baseline-shop is this connector's acceptance test: the shop of
// deploy/kind/otel-demo/minimal, delivered as one informer list, must produce the forty events
// fixtures/baseline-topology-01 records for `k8s:demo`. TestBaselineMatchesPublishedFixture
// compares the two line by line and says exactly where they differ and why.

// testFeeder is the feeder under the synthetic corpora's configuration.
func testFeeder(t *testing.T) *k8sfeeder.Feeder {
	t.Helper()
	f, err := k8sfeeder.New(fixtureOptions(), nil)
	if err != nil {
		t.Fatalf("new feeder: %v", err)
	}
	return f
}

// kindFeeder is the feeder as the live run of 2026-09-16 configured it, which is the command
// line deploy/kind/README.md documents. testdata/kind-shop was recorded through it, so nothing
// but these options reproduces that corpus.
func kindFeeder(t *testing.T) *k8sfeeder.Feeder {
	t.Helper()
	f, err := k8sfeeder.New(kindOptions(), nil)
	if err != nil {
		t.Fatalf("new feeder: %v", err)
	}
	return f
}

// kindShopDir is the recorded corpus of the live run.
const kindShopDir = "testdata/kind-shop"

func kindOptions() k8sfeeder.Options {
	return k8sfeeder.Options{
		SourceID:    "k8s:kind",
		ClusterName: "sre-agent-demo",
		Namespaces:  []string{"shop"},
		OwnerLabels: []string{"team"},
		Environment: "prod",
		// The kind recording and fixtures/baseline-topology-01 were both taken before
		// ADR-0005 D6 added `Pointer.join_keys`, so they are replayed under the pointer shape
		// they were recorded with — the same move IDFormatCompat makes for the otel baseline.
		// A live run emits the join keys; the corpora generated by TestGenerateTestdata are
		// recorded with them and prove it. See feeder.PointerCompat.
		PointerCompat: feeder.PointerCompatNoJoinKeys,
	}
}

// TestConformanceKindShop is the recorded half of this connector's acceptance (T058,
// constitution VIII: "synthetic-only test data is insufficient for a connector to be marked
// stable"). testdata/kind-shop/payloads are the bytes real informers delivered from a kind
// cluster; replaying them must produce the events recorded beside them.
func TestConformanceKindShop(t *testing.T) {
	t.Run("run", func(t *testing.T) { testkit.Run(t, kindFeeder(t), kindShopDir) })
	t.Run("double-deliver", func(t *testing.T) { testkit.DoubleDeliver(t, kindFeeder(t), kindShopDir) })
}

func TestConformanceKindShopAgainstAGraph(t *testing.T) {
	withGraph := testkit.WithEmitter(func(t *testing.T, d feeder.Description) testkit.ResultEmitter {
		return emit.NewProjectorEmitter(projector.New(pgtest.Open(t)), d)
	})
	t.Run("run", func(t *testing.T) { testkit.Run(t, kindFeeder(t), kindShopDir, withGraph) })
	t.Run("double-deliver", func(t *testing.T) { testkit.DoubleDeliver(t, kindFeeder(t), kindShopDir, withGraph) })
}

// TestConformanceKindShopShuffle is the third leg of testkit.Conformance, and it is the test
// that was skipped for the whole of the live run of 2026-09-16.
//
// The synthetic corpora hid the problem because every payload in them carries the same whole-
// second arrival time, so permuting them inside the 60s reordering window permutes nothing that
// matters. A real informer list does not: the 32 payloads of testdata/kind-shop arrive
// microseconds apart, and the feeder used to stamp the initial list's `valid_at` — and the
// extent of the checkpoint that closed it — from the arrival time of whichever payload it saw
// first. Reordering them moved every initial-list fact by a few microseconds, which is a
// valid-time state that depends on arrival order: FR-021 and FR-048 say it must not be.
//
// What fixed it is in three places and none of them is here. The initial list carries FR-011's
// unknown start instead of a guessed instant (Feeder.validFor); the checkpoint that closes it
// takes its extent from the marker payloads rather than from the earliest and latest arrival
// (Feeder.closeListAt); and an object seen within ListSettle of the marker is initial state
// however late the informers' own dispatch delivered it. Six seeded permutations now emit the
// same 63 events.
func TestConformanceKindShopShuffle(t *testing.T) {
	testkit.Shuffle(t, kindFeeder(t), kindShopDir)
}

func TestConformanceBaselineShop(t *testing.T) {
	testkit.Conformance(t, testFeeder(t), filepath.Join("testdata", "baseline-shop"))
}

// TestConformanceBaselineShopAgainstAGraph re-runs the same checks with a real projector over a
// test database beside the in-memory emitter, so that "the graph accepts this" is proven by the
// graph rather than by the SDK's copy of its validator.
func TestConformanceBaselineShopAgainstAGraph(t *testing.T) {
	testkit.Conformance(t, testFeeder(t), filepath.Join("testdata", "baseline-shop"),
		testkit.WithShuffles(2),
		testkit.WithEmitter(func(t *testing.T, d feeder.Description) testkit.ResultEmitter {
			return emit.NewProjectorEmitter(projector.New(pgtest.Open(t)), d)
		}))
}

// TestConformanceRolloutScaleConfig replays the same list followed by four things happening: a
// rollout named by its revision, a scale-up attributed to an autoscaler, a ConfigMap edit that
// reaches the workload consuming it, and the deletion of a Service, which retracts the exposure
// through it without deleting anything from history (constitution II).
func TestConformanceRolloutScaleConfig(t *testing.T) {
	testkit.Conformance(t, testFeeder(t), filepath.Join("testdata", "rollout-scale-config"))
}

func TestConformanceRolloutScaleConfigAgainstAGraph(t *testing.T) {
	testkit.Conformance(t, testFeeder(t), filepath.Join("testdata", "rollout-scale-config"),
		testkit.WithShuffles(2),
		testkit.WithEmitter(func(t *testing.T, d feeder.Description) testkit.ResultEmitter {
			return emit.NewProjectorEmitter(projector.New(pgtest.Open(t)), d)
		}))
}

// TestDescribe pins the contract the graph and the harness are held to.
func TestDescribe(t *testing.T) {
	desc := testFeeder(t).Describe()
	if desc.Kind != "k8s" {
		t.Errorf("Kind = %q, want k8s", desc.Kind)
	}
	if desc.Ordering != feeder.OrderingPerSourceSequence {
		t.Errorf("Ordering = %q, want %q", desc.Ordering, feeder.OrderingPerSourceSequence)
	}
	if desc.ReorderingWindow != k8sfeeder.DefaultReorderingWindow {
		t.Errorf("ReorderingWindow = %s, want %s", desc.ReorderingWindow, k8sfeeder.DefaultReorderingWindow)
	}
	if err := desc.Validate(); err != nil {
		t.Errorf("Validate: %v", err)
	}
	// Every namespace the feeder says it will mint identities in must be one the SDK
	// publishes, or another connector cannot meet it (FR-036).
	for _, ns := range desc.Namespaces {
		if !feeder.IsWellKnownNamespace(ns) {
			t.Errorf("Describe declares namespace %q, which pkg/feeder does not publish", ns)
		}
	}
	// A scope this feeder asks for that is not read-only would be a contradiction of the
	// refusal in permissions.go (FR-046).
	for _, scope := range desc.RequiredScopes {
		verbs, _, _ := strings.Cut(scope, " on ")
		for _, verb := range strings.Split(verbs, ",") {
			switch verb {
			case "get", "list", "watch":
			case "create":
				if !strings.Contains(scope, "selfsubjectrulesreviews") {
					t.Errorf("required scope %q asks to create something other than a rules review", scope)
				}
			default:
				t.Errorf("required scope %q is not read-only", scope)
			}
		}
	}
}

// TestCorpusManifests keeps the manifests honest: they are loaded by the same strict loader
// `fixture verify` uses, and what they declare about the feeder must be what the feeder
// declares about itself.
func TestCorpusManifests(t *testing.T) {
	corpora := map[string]func(*testing.T) *k8sfeeder.Feeder{
		"baseline-shop":        testFeeder,
		"rollout-scale-config": testFeeder,
		"kind-shop":            kindFeeder,
	}
	for _, dir := range []string{"baseline-shop", "kind-shop", "rollout-scale-config"} {
		t.Run(dir, func(t *testing.T) {
			manifest, err := fixture.LoadManifest(filepath.Join("testdata", dir))
			if err != nil {
				t.Fatalf("load manifest: %v", err)
			}
			if manifest.ID != dir {
				t.Errorf("id = %q, want the directory name %q", manifest.ID, dir)
			}
			desc := corpora[dir](t).Describe()
			if len(manifest.Sources) != 1 {
				t.Fatalf("declares %d sources, want 1", len(manifest.Sources))
			}
			src := manifest.Sources[0]
			if src.SourceID != desc.SourceID || src.Kind != desc.Kind ||
				src.Ordering != desc.Ordering.String() || src.ReorderingWindow != desc.ReorderingWindow {
				t.Errorf("manifest source %+v does not match Describe() %+v", src, desc)
			}
		})
	}
}

// TestNoSecretMaterialInTheCorpus is SC-009 as a test over the recorded bytes rather than over
// the code that wrote them: whatever the payload recorder did, neither the committed corpus nor
// any shipped fixture may contain the demo Secret's value.
//
// It also refuses `kubectl.kubernetes.io/last-applied-configuration` anywhere in a recorded
// Secret payload. That annotation is how the material got onto disk in the first place — it
// holds the whole submitted manifest, `stringData` and all, and `RedactSecret` used to copy
// metadata untouched (live run 2026-09-16, finding 5). Asserting the value is absent would not
// have caught it on a cluster whose Secret happened to hold a different string; asserting the
// annotation is absent catches the class.
func TestNoSecretMaterialInTheCorpus(t *testing.T) {
	const material = "not-a-real-token-disposable-demo-cluster"
	var files []string
	for _, dir := range []string{"baseline-shop", "kind-shop", "rollout-scale-config"} {
		files = append(files,
			filepath.Join("testdata", dir, "events.jsonl"),
			filepath.Join("testdata", dir, "payloads", "secrets", "000001.json"))
	}
	// The shipped fixtures are recordings of this feeder and are published in the same
	// repository, so they are held to the same rule (SC-009, constitution IV).
	shipped, err := filepath.Glob(filepath.Join("..", "..", "..", "fixtures", "*", "payloads", "secrets", "*.json"))
	if err != nil {
		t.Fatalf("glob the shipped fixtures: %v", err)
	}
	if len(shipped) == 0 {
		t.Fatal("no shipped fixture records a Secret payload; this test is checking nothing")
	}
	files = append(files, shipped...)

	for _, path := range files {
		raw, err := readIfPresent(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		if strings.Contains(string(raw), material) {
			t.Errorf("%s contains the Secret's value; a recording must carry versions, never material", path)
		}
		if strings.Contains(filepath.ToSlash(path), "/secrets/") &&
			strings.Contains(string(raw), k8sfeeder.LastAppliedAnnotation) {
			t.Errorf("%s mentions %s; that annotation holds the submitted manifest, stringData included",
				path, k8sfeeder.LastAppliedAnnotation)
		}
	}
}

// publishedFixture is the event stream fixtures/baseline-topology-01 records for this feeder's
// source. Since T058 it is a recording of this feeder, not a description of it.
const publishedFixture = "../../../fixtures/baseline-topology-01/events.jsonl"

// knownDivergence is one recorded event this feeder cannot reproduce byte for byte, and why.
//
// It used to have forty entries. Every one of them was a property of the *hand-authored*
// fixture rather than a shortcut in the feeder: that stream numbered its events from a single
// counter across the whole file, so an edge got an `@rv` belonging to no object, while a
// feeder's identifiers must be pure functions of the objects they describe or re-delivery
// stops being a no-op (FR-018, FR-020). T058 replaced the hand-authored file with a real
// recording of this feeder and the list became empty, which is what it said would happen.
//
// It is kept, empty, because it is still the right place to put a divergence that a future
// re-recording legitimately introduces — and because TestRecordedFixtureIsThisFeedersOutput
// fails on an entry that has gone away, so a stale one cannot rot here unnoticed.
type knownDivergence struct {
	// line is the 1-based position in the fixture's `k8s:kind` stream.
	line int
	// fields are the top-level or property names that differ.
	fields []string
	// why is the reason, in a sentence. Unused while the table is empty, and kept because an
	// entry without a reason is the thing this list exists to prevent.
	why string //nolint:unused // read by the reviewer of the next entry, not by the test
}

var knownDivergences = []knownDivergence{}

// TestRecordedFixtureIsThisFeedersOutput is the acceptance test of T057, restated by T058.
//
// Before the live run it asked a weaker question — does the feeder agree with a fixture a human
// wrote? — and answered it with a forty-entry excuse list. Now fixtures/baseline-topology-01 is
// a recording of this feeder from a real cluster, so the question is the one that matters: does
// replaying the payloads that fixture ships through this feeder still produce the events it
// ships? That is FR-044's "identical output in live and recorded modes" for the shipped
// artifact rather than for a test corpus.
//
// It fails on any difference not in knownDivergences, including a divergence that has gone
// away, so the list shrinks as the fixture is re-recorded rather than rotting.
func TestRecordedFixtureIsThisFeedersOutput(t *testing.T) {
	recorded, err := fixture.ReadEvents(publishedFixture)
	if err != nil {
		t.Fatalf("read %s: %v", publishedFixture, err)
	}
	var want []*graphv1.EventEnvelope
	for _, event := range recorded {
		if event.Envelope.GetSourceId() == kindOptions().SourceID {
			want = append(want, event.Envelope)
		}
	}
	if len(want) == 0 {
		t.Fatalf("%s records no events for %s; the fixture and this feeder have drifted apart",
			publishedFixture, kindOptions().SourceID)
	}

	// Replaying the fixture's own k8s payloads is what produces `got` — the corpus beside this
	// test is the same bytes, and testkit.Conformance already proves the two agree, so reading
	// it here keeps this test about the fixture rather than about file copying.
	got, err := fixture.ReadEvents(filepath.Join("testdata", "kind-shop", "events.jsonl"))
	if err != nil {
		t.Fatalf("read the corpus: %v", err)
	}
	if len(want) != len(got) {
		t.Fatalf("the published fixture records %d events for %s, the corpus has %d",
			len(want), kindOptions().SourceID, len(got))
	}

	expected := map[int][]string{}
	for _, d := range knownDivergences {
		expected[d.line] = d.fields
	}
	for i := range want {
		line := i + 1
		fields := diffFields(t, want[i], got[i].Envelope)
		allowed := expected[line]
		if !slices.Equal(fields, allowed) {
			t.Errorf("event %d (%s) differs in %v, the documented divergence is %v",
				line, want[i].GetEventId(), fields, allowed)
		}
	}
}

// diffFields names every top-level field and every property in which two events differ, sorted.
func diffFields(t *testing.T, want, got *graphv1.EventEnvelope) []string {
	t.Helper()
	a, b := decode(t, want), decode(t, got)
	fields := map[string]bool{}
	for key := range union(a, b) {
		if key == "idempotencyKey" {
			// The idempotency key is the event id by convention, so it never diverges on its
			// own and reporting it twice would only make the list longer.
			continue
		}
		if fmt.Sprint(a[key]) == fmt.Sprint(b[key]) {
			continue
		}
		body, bodyOK := a[key].(map[string]any)
		other, otherOK := b[key].(map[string]any)
		if bodyOK && otherOK {
			for _, prop := range diffProps(body, other) {
				fields[prop] = true
			}
			if len(diffProps(body, other)) > 0 {
				continue
			}
		}
		fields[key] = true
	}
	out := make([]string, 0, len(fields))
	for key := range fields {
		out = append(out, key)
	}
	slices.Sort(out)
	return out
}

// diffProps names the differing entries of two events' `props`, or nothing when the bodies
// differ in some other way.
func diffProps(a, b map[string]any) []string {
	propsA, okA := a["props"].(map[string]any)
	propsB, okB := b["props"].(map[string]any)
	if !okA || !okB {
		return nil
	}
	if fmt.Sprint(withoutProps(a)) != fmt.Sprint(withoutProps(b)) {
		return nil
	}
	var out []string
	for key := range union(propsA, propsB) {
		if fmt.Sprint(propsA[key]) != fmt.Sprint(propsB[key]) {
			out = append(out, key)
		}
	}
	slices.Sort(out)
	return out
}

func withoutProps(m map[string]any) string {
	copied := map[string]any{}
	for k, v := range m {
		if k != "props" {
			copied[k] = v
		}
	}
	keys := make([]string, 0, len(copied))
	for k := range copied {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	var b strings.Builder
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%v;", k, copied[k])
	}
	return b.String()
}

func union(a, b map[string]any) map[string]struct{} {
	out := map[string]struct{}{}
	for k := range a {
		out[k] = struct{}{}
	}
	for k := range b {
		out[k] = struct{}{}
	}
	return out
}

func decode(t *testing.T, ev *graphv1.EventEnvelope) map[string]any {
	t.Helper()
	raw, err := graph.CanonicalJSON(ev)
	if err != nil {
		t.Fatalf("canonical json: %v", err)
	}
	var out map[string]any
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("decode canonical json: %v", err)
	}
	return out
}

// readIfPresent reads a file, returning nothing for one a corpus does not have.
func readIfPresent(path string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	return raw, err
}
