// SPDX-License-Identifier: Apache-2.0

package sanitise

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"
)

// The signed manifest (T155; FR-140, contracts/sanitisation.md §6 gate 3).
//
// FR-140: *"Every committed recording MUST carry a signed manifest stating the sanitisation policy
// version, the content hash of what was signed, the named individual who signed it off, the date and
// what was dropped; and, where a second person exists, a second signature."*
//
// ---------------------------------------------------------------------------------------------
// This is an attestation, not a cryptographic signature, and the difference is the point
//
// A `Signature` here is a person's name and a date. Nothing is verified against a key, and a reader
// who assumed otherwise would trust this more than it deserves — so the type says so, the written
// file says so, and there is no `Verify` method to imply a check that does not happen.
//
// That is not a shortcut. What FR-140 is for is **accountability**: somebody looked at what was
// about to be committed and put their name to it. A cryptographic signature would prove the manifest
// was not altered after signing, which is a different property and one the git history already
// provides. What no key can provide is a person having read it.
//
// # What the content hash covers, and why it is not the manifest
//
// "The content hash of what was signed" — so the hash is over the recording, every committed byte of
// it, not over the manifest describing it. A hash of the manifest would be a signature on a
// *description*: change a payload and the manifest still matches itself.
//
// So `HashRecording` walks the directory, hashes each file's path and contents in a fixed order, and
// produces one digest. Paths are included because a file moved between directories is a different
// recording even with identical bytes, and the manifest itself is excluded because it carries the
// hash — a hash covering the file it lives in cannot be computed.
//
// # Why "where a second person exists" cannot be decided here
//
// A manifest cannot know whether the organisation has a second person. Nothing in a directory says
// so. So the count is **declared** in the campaign record's signatories, and `Check` takes it: with
// two or more signatories declared, one signature is refused. The alternative — a flag on the
// command — is how a one-person sign-off gets waved through on a team of five.

// ManifestFile is the signed manifest's name inside a recording directory. It sits beside the
// fixture manifest rather than inside it: the fixture manifest is regenerated by `fixture record`,
// and a regeneration that silently reset the signatures would defeat the gate.
const ManifestFile = "sanitisation.yaml"

// Signature is one person's sign-off. See the type comment above: a name and a date, not a key.
type Signature struct {
	// By is the named individual. FR-140 wants a person; a team name is refused, because "platform"
	// did not read anything.
	By string `yaml:"by"`
	// On is the date they signed.
	On time.Time `yaml:"on"`
	// Note is what they want recorded about what they were signing — typically the disclosure they
	// accepted. §4's unfuzzed timestamps are the standing example: a signatory is accepting that the
	// corpus discloses roughly when this organisation deploys.
	Note string `yaml:"note,omitempty"`
}

// DroppedField is one field the sanitiser dropped rather than recorded. FR-140's "what was dropped"
// is a list, not a count: a reviewer deciding whether the drop was right needs to know which field.
type DroppedField struct {
	Field string `yaml:"field"`
	Why   string `yaml:"why"`
}

// DroppedPayload is a whole payload that could not be made safe and was therefore dropped.
//
// It is separate from DroppedField because the two mean different things to a reviewer. A dropped
// field is the contract working — that is what a `drop` disposition is. A dropped payload is a gap
// in the recording, and a gap that nobody wrote down is indistinguishable from a period the campaign
// was not running (the same confusion FR-130 exists to prevent one instance of).
type DroppedPayload struct {
	Name string `yaml:"name"`
	Why  string `yaml:"why"`
}

// Manifest is the signed manifest.
type Manifest struct {
	// PolicyVersion is the sanitisation contract version the recording was made under (FR-134).
	PolicyVersion string `yaml:"policy_version"`
	// ContentHash is HashRecording's digest over every committed file. Prefixed with its algorithm,
	// so a later change of algorithm is visible in the file rather than silently comparing unlike
	// digests.
	ContentHash string `yaml:"content_hash"`
	// Recording names what was hashed, relative to the recording directory, in hash order, each
	// with its own digest. It is recorded so a reader can tell a hash mismatch caused by an edited
	// file from one caused by a file added or removed — and, because each file carries its own
	// hash, WHICH file it was. Without the per-file digest a mismatch in an unchanged file set can
	// only be reported as "one of these was edited", which on a corpus of hundreds of files is not
	// something a reviewer can act on.
	Recording []RecordedFile `yaml:"recording"`
	// Signatures are the sign-offs, in order.
	Signatures []Signature `yaml:"signatures"`
	// DroppedFields and DroppedPayloads are FR-140's "what was dropped", in its two senses.
	DroppedFields   []DroppedField   `yaml:"dropped_fields,omitempty"`
	DroppedPayloads []DroppedPayload `yaml:"dropped_payloads,omitempty"`
	// Canaries is how many canary tokens were seeded before the campaign (FR-139). Zero is
	// recorded rather than omitted, because "no canaries were seeded" and "the field is missing"
	// are different facts and only one of them is a gate that did not run.
	Canaries int `yaml:"canaries_seeded"`
	// Attestation states what a signature here does and does not mean. It is a field rather than a
	// comment so that it travels with the file into the private repository.
	Attestation string `yaml:"attestation"`
}

// AttestationText is what every manifest carries in its Attestation field.
const AttestationText = "A signature here is a named person's attestation that they reviewed what " +
	"was committed under the stated policy version, including the disclosures the policy accepts " +
	"(contracts/sanitisation.md §4). It is not a cryptographic signature and nothing verifies it " +
	"against a key; what it records is that somebody read this, which no key can record."

// hashAlgorithm prefixes ContentHash.
const hashAlgorithm = "sha256"

// ErrUnsigned is returned for a manifest with no signature at all.
var ErrUnsigned = errors.New("sanitise: a recording with no signature; FR-140 requires a NAMED " +
	"individual to have signed it off, and an unsigned recording is one nobody took responsibility for")

// ErrSecondSignatureMissing is returned when the campaign declares more than one signatory and only
// one has signed.
var ErrSecondSignatureMissing = errors.New("sanitise: the campaign declares more than one " +
	"signatory and only one has signed; FR-140 requires a second signature where a second person " +
	"exists, and the point of taking the count from the campaign record is that a single sign-off " +
	"cannot wave itself through")

// NewManifest builds a manifest for a recording directory.
//
// It hashes the recording as part of building, rather than taking a hash from the caller, because a
// caller-supplied hash is a hash of whatever the caller looked at — which is not necessarily what is
// on disk about to be committed.
func NewManifest(dir, policyVersion string, signatures []Signature, dropped []Drop, droppedPayloads []DroppedPayload, canaries int) (Manifest, error) {
	if strings.TrimSpace(policyVersion) == "" {
		return Manifest{}, errors.New("sanitise: a manifest needs the policy version it was made " +
			"under; without it a reader cannot tell which contract the recording satisfies (FR-134)")
	}
	hash, files, err := HashRecording(dir)
	if err != nil {
		return Manifest{}, err
	}
	if len(files) == 0 {
		return Manifest{}, fmt.Errorf("sanitise: %s holds nothing to sign; a manifest over an empty "+
			"recording would attest to no content at all", dir)
	}

	// DroppedField and Drop are field-identical, so the conversion is direct. They stay separate
	// types because Drop is the sanitiser'''s running tally and DroppedField is what a manifest
	// commits to: the first is working state, the second is a published artifact, and letting the
	// manifest depend on the tally'''s shape would make a refactor of one a change to the other.
	fields := make([]DroppedField, 0, len(dropped))
	for _, d := range dropped {
		fields = append(fields, DroppedField(d))
	}
	sort.Slice(fields, func(i, j int) bool { return fields[i].Field < fields[j].Field })

	payloads := slices.Clone(droppedPayloads)
	sort.Slice(payloads, func(i, j int) bool { return payloads[i].Name < payloads[j].Name })

	return Manifest{
		PolicyVersion:   policyVersion,
		ContentHash:     hash,
		Recording:       files,
		Signatures:      slices.Clone(signatures),
		DroppedFields:   fields,
		DroppedPayloads: payloads,
		Canaries:        canaries,
		Attestation:     AttestationText,
	}, nil
}

// RecordedFile is one committed file of a recording, with its own digest.
//
// The per-file hash is what makes a failed verification actionable. The manifest's single
// `content_hash` answers "has anything moved"; only a per-file digest answers "which file", and a
// reviewer told that one of several hundred files was edited after signing has been told nothing
// they can act on. The overall hash is still the gate — this is how the gate explains itself.
type RecordedFile struct {
	// Path is the file's path relative to the recording directory, slash-separated.
	Path string `yaml:"path"`
	// SHA256 is the digest of that file's contents alone.
	SHA256 string `yaml:"sha256"`
}

// Check is the COMMIT gate: the manifest's shape, plus the number of signatories the campaign
// declared.
//
// `declaredSignatories` comes from the campaign record. Passing 0 means the campaign declared none,
// which is itself a failure: FR-140 needs a name, and a campaign that names nobody cannot produce one.
func (m Manifest) Check(declaredSignatories int) error {
	if err := m.CheckShape(); err != nil {
		return err
	}
	if declaredSignatories <= 0 {
		return errors.New("sanitise: the campaign declares no signatory, so no manifest it " +
			"produces can satisfy FR-140")
	}
	if declaredSignatories > 1 && len(m.Signatures) < 2 {
		return ErrSecondSignatureMissing
	}
	return nil
}

// CheckShape validates everything about a manifest that does not depend on the campaign: the policy
// version, the hash, the file list, the attestation, and that each signature names a distinct person
// with a date.
//
// It is separate from Check because writing and committing are different moments. A two-person
// campaign's first signature is written while the commit gate is still unsatisfied, and a write that
// enforced the count would make the second signature unreachable.
func (m Manifest) CheckShape() error {
	if strings.TrimSpace(m.PolicyVersion) == "" {
		return errors.New("sanitise: a manifest with no policy version (FR-134)")
	}
	if !strings.HasPrefix(m.ContentHash, hashAlgorithm+":") {
		return fmt.Errorf("sanitise: content hash %q does not name its algorithm; an unprefixed "+
			"digest silently compares unlike against one from another algorithm", m.ContentHash)
	}
	if len(m.Recording) == 0 {
		return errors.New("sanitise: a manifest naming no files; the hash would then be over " +
			"nothing anybody can check")
	}
	if strings.TrimSpace(m.Attestation) == "" {
		return errors.New("sanitise: a manifest with no attestation text; a reader would take a " +
			"name and a date for a cryptographic signature")
	}
	if len(m.Signatures) == 0 {
		return ErrUnsigned
	}
	seen := map[string]bool{}
	for i, s := range m.Signatures {
		if strings.TrimSpace(s.By) == "" {
			return fmt.Errorf("sanitise: signature %d names nobody; FR-140 wants a named individual", i+1)
		}
		if s.On.IsZero() {
			return fmt.Errorf("sanitise: signature %d by %q has no date", i+1, s.By)
		}
		key := strings.ToLower(strings.TrimSpace(s.By))
		if seen[key] {
			return fmt.Errorf("sanitise: %q signed twice; two signatures from one person are one "+
				"signature, and counting them as two is how the second-signature rule is defeated", s.By)
		}
		seen[key] = true
	}
	return nil
}

// Verify re-hashes the recording and reports whether it still matches the manifest.
//
// It names *what* changed rather than only that something did: a file added, a file removed, or the
// contents of one edited. "The hash does not match" sends a reviewer looking through the whole
// directory; "payloads/services/000002.json was added since signing" sends them to the file.
func (m Manifest) Verify(dir string) error {
	hash, files, err := HashRecording(dir)
	if err != nil {
		return err
	}
	if hash == m.ContentHash {
		return nil
	}
	signed := make(map[string]string, len(m.Recording))
	for _, f := range m.Recording {
		signed[f.Path] = f.SHA256
	}
	var added, removed, edited []string
	for _, f := range files {
		was, ok := signed[f.Path]
		switch {
		case !ok:
			added = append(added, f.Path)
		case was != f.SHA256:
			edited = append(edited, f.Path)
		}
		delete(signed, f.Path)
	}
	for path := range signed {
		removed = append(removed, path)
	}
	sort.Strings(added)
	sort.Strings(removed)
	sort.Strings(edited)

	var parts []string
	if len(edited) > 0 {
		parts = append(parts, "edited since signing: "+strings.Join(edited, ", "))
	}
	if len(added) > 0 {
		parts = append(parts, "added since signing: "+strings.Join(added, ", "))
	}
	if len(removed) > 0 {
		parts = append(parts, "removed since signing: "+strings.Join(removed, ", "))
	}
	if len(parts) == 0 {
		// The file set and every file's digest agree, and the overall hash does not. That is not a
		// recording that moved — it is a manifest whose content_hash was written by something other
		// than HashRecording, or edited by hand. Saying "one file was edited" here would send a
		// reviewer to look for a change that is not in the files.
		return fmt.Errorf("sanitise: %s matches its manifest file by file, but the manifest's "+
			"content_hash is %s and the recording hashes to %s — the hash was not produced by this "+
			"recording, so the manifest attests to something that was never on disk",
			dir, m.ContentHash, hash)
	}
	return fmt.Errorf("sanitise: %s no longer matches its signed manifest: %s",
		dir, strings.Join(parts, "; "))
}

// HashRecording returns a digest over every committed file in dir, and each file with its own digest.
//
// The overall digest is over `len(path) path len(contents) contents` for each file, in lexical path
// order. The lengths are what stop two different recordings hashing alike: without them, a file named
// `ab` holding `c` and one named `a` holding `bc` are the same byte stream.
//
// Each file's own SHA-256 is computed from the same read, which is what lets Verify name the file
// that changed rather than only report that something did.
//
// The manifest itself is excluded, because it carries the hash.
func HashRecording(dir string) (string, []RecordedFile, error) {
	var paths []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if rel == ManifestFile {
			return nil
		}
		paths = append(paths, rel)
		return nil
	})
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return "", nil, fmt.Errorf("sanitise: %s does not exist, so there is nothing to hash", dir)
		}
		return "", nil, fmt.Errorf("sanitise: walk %s: %w", dir, err)
	}
	sort.Strings(paths)

	sum := sha256.New()
	out := make([]RecordedFile, 0, len(paths))
	for _, rel := range paths {
		fmt.Fprintf(sum, "%d:%s:", len(rel), rel)
		f, err := os.Open(filepath.Join(dir, rel)) //nolint:gosec // a path from walking dir
		if err != nil {
			return "", nil, fmt.Errorf("sanitise: open %s: %w", rel, err)
		}
		info, err := f.Stat()
		if err != nil {
			_ = f.Close()
			return "", nil, fmt.Errorf("sanitise: stat %s: %w", rel, err)
		}
		fmt.Fprintf(sum, "%d:", info.Size())
		// One read feeds both digests: the recording's, and this file's own. Reading twice would
		// let the two disagree if the file changed between them, which is the one case the gate
		// exists for.
		own := sha256.New()
		if _, err := io.Copy(io.MultiWriter(sum, own), f); err != nil {
			_ = f.Close()
			return "", nil, fmt.Errorf("sanitise: read %s: %w", rel, err)
		}
		if err := f.Close(); err != nil {
			return "", nil, fmt.Errorf("sanitise: close %s: %w", rel, err)
		}
		out = append(out, RecordedFile{
			Path:   rel,
			SHA256: hashAlgorithm + ":" + hex.EncodeToString(own.Sum(nil)),
		})
	}
	return hashAlgorithm + ":" + hex.EncodeToString(sum.Sum(nil)), out, nil
}
