// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"google.golang.org/protobuf/types/known/timestamppb"

	graphv1 "github.com/Pierre-Theophile/aisre/api/sreagent/graph/v1"
	investigationv1 "github.com/Pierre-Theophile/aisre/api/sreagent/investigation/v1"
	"github.com/Pierre-Theophile/aisre/internal/graph"
	algebra "github.com/Pierre-Theophile/aisre/internal/investigation/backend"
	"github.com/Pierre-Theophile/aisre/internal/query"
	"github.com/Pierre-Theophile/aisre/internal/store/postgres"
	sdk "github.com/Pierre-Theophile/aisre/pkg/backend"
	"github.com/Pierre-Theophile/aisre/pkg/backend/synthetic"
)

// `worker record` — recording a world (tasks.md T039, FR-042b, plan F8, research §9).
//
// A world is the **cross product of the telemetry algebra over the alert's neighbourhood and the
// window grid, plus the depth-1 drill-downs those answers mint**. It is not a trajectory: it is a
// map from a question to an answer, so a replayed investigation that takes a different reasoning
// path is still served. That is the whole claim of US3, and it is why the enumeration below is
// exhaustive rather than driven by what some run happened to ask.
//
// What gets enumerated, in order:
//
//  1. the neighbourhood: every node within `--hops` of the focus, from 001's Subgraph;
//  2. every pointer on every one of those nodes, from 001's Pointers — the pointers are the
//     graph's own statement of where a node's telemetry lives, which is what makes this finite;
//  3. every telemetry term over every (pointer × window-grid entry) pair, and `error_spans` over
//     every edge on the path set;
//  4. every drill-down handle those answers minted, followed **once**. Depth 2 and beyond answer
//     NOT_RECORDED by design, and the depth is written into the index so a fixture states its own
//     limit rather than hiding it.
//
// The graph family is **not** recorded. Graph answers come from replaying `events.jsonl`, which
// 001 already guarantees is byte-reproducible; recording them would create a second source of
// truth for the same answer (research §9).
//
// **The telemetry itself comes from the synthetic backend** in this build — a stand-in that
// derives deterministic series, logs and spans from the fixture's own graph. Feature 003's GCP
// backend records the first real world. Until then a fixture recorded here carries
// `provenance: synthetic`, and pkg/backend/synthetic says so at length.

// recordedStatistics is the statistic set the cross product covers. It is deliberately small:
// every statistic multiplies the world by the number of pointers and windows, and these three
// answer the questions the first wave actually asks — is it failing, is it slow, is it busy.
var recordedStatistics = []investigationv1.Statistic{
	investigationv1.Statistic_ERROR_RATE,
	investigationv1.Statistic_P95,
	investigationv1.Statistic_RATE,
}

type workerRecordOptions struct {
	out     string
	focus   string
	window  string
	hops    int
	grid    string
	dsn     string
	culprit string
	seed    string
}

func newWorkerRecordCommand(global *globalOptions) *cobra.Command {
	opts := &workerRecordOptions{}

	cmd := &cobra.Command{
		Use:   "record",
		Short: "Record a world: the cross product of the telemetry algebra over a neighbourhood and a window grid",
		Long: "record writes `world/index.json` and one `world/<term_key>.json` per answer, in the published\n" +
			"layout (contracts/incident-format.md). The recorded set is the telemetry family of the\n" +
			"algebra over every pointer on every node within --hops of --focus, crossed with the window\n" +
			"grid, plus every depth-1 drill-down those answers mint.\n\n" +
			"A re-record of an unchanged graph is byte-identical: the enumeration is ordered, the\n" +
			"generator is deterministic and the index digest is checked on load.\n\n" +
			"The telemetry is generated by the synthetic backend from the graph itself — a stand-in\n" +
			"until feature 003's GCP backend records a real world. A fixture recorded this way carries\n" +
			"`provenance: synthetic` and no accuracy claim resting on it may be published as though it\n" +
			"rested on a recording.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runWorkerRecord(cmd, global, opts)
		},
	}

	flags := cmd.Flags()
	flags.StringVar(&opts.out, "out", "", "directory to write the world into (required)")
	flags.StringVar(&opts.focus, "focus", "", "focus node as <namespace>=<value> (required)")
	flags.StringVar(&opts.window, "window", "", "T1..T2 in RFC 3339 (required)")
	flags.IntVar(&opts.hops, "hops", 2, "neighbourhood radius")
	flags.StringVar(&opts.grid, "grid", "900,3600",
		"window grid: comma-separated half-widths in seconds around the window end, or <rfc3339>@<seconds> entries")
	flags.StringVar(&opts.dsn, "db", "", "PostgreSQL DSN holding the graph (default $"+EnvDSN+")")
	flags.StringVar(&opts.culprit, "culprit", "",
		"entity id of the change that degrades its targets, so the generated telemetry agrees with the fixture's ground truth; never guessed")
	flags.StringVar(&opts.seed, "seed", "",
		"generator seed (default: the focus reference), which makes one fixture's telemetry differ from another's")

	return cmd
}

func runWorkerRecord(cmd *cobra.Command, global *globalOptions, opts *workerRecordOptions) error {
	if opts.out == "" || opts.focus == "" || opts.window == "" {
		return exitErrorf(ExitUsage, "worker record needs --out, --focus and --window")
	}
	focus, err := graph.ParseRef(opts.focus)
	if err != nil {
		return exitErrorf(ExitUsage, "--focus %q: %v", opts.focus, err)
	}
	from, to, err := parseWindowSpec(opts.window)
	if err != nil {
		return exitWith(ExitUsage, err)
	}
	grid, err := parseGridSpec(opts.grid, to)
	if err != nil {
		return exitWith(ExitUsage, err)
	}
	dsn, err := dsnFrom(opts.dsn, os.Getenv(EnvDSN))
	if err != nil {
		return err
	}
	store, err := postgres.Open(cmd.Context(), dsn)
	if err != nil {
		return storeError("open database", err)
	}
	defer store.Close()

	spec := worldSpec{
		Focus:     focus,
		From:      from,
		To:        to,
		Hops:      opts.hops,
		Grid:      grid,
		Culprits:  splitCommas(opts.culprit),
		Seed:      firstNonEmpty(opts.seed, opts.focus),
		OutputDir: opts.out,
	}
	report, err := recordWorld(cmd.Context(), query.NewEngine(store), spec)
	if err != nil {
		return exitWith(ExitTransport, err)
	}
	return renderWorldReport(cmd, global, report)
}

// worldSpec is everything a recording needs. `fixture record-world` fills it from a fixture's own
// manifest rather than from flags, so a re-record cannot silently change a fixture's shape.
type worldSpec struct {
	// Focus is the node the neighbourhood is taken around.
	Focus graph.Ref
	// From and To bound the graph diff the changes are read from.
	From time.Time
	// To is the reference instant and the end of the diff window.
	To time.Time
	// Hops is the neighbourhood radius.
	Hops int
	// Grid is the before/after pairs the cross product is taken over.
	Grid []*investigationv1.WindowPair
	// Culprits are the change entity ids whose targets degrade. They are supplied, never
	// inferred: a recorder that guessed which change was the culprit would be writing the
	// answer into the question.
	Culprits []string
	// Seed makes one fixture's generated telemetry differ from another's.
	Seed string
	// Horizon is the investigation's `observed_at`: the instant past which this fixture has no
	// telemetry (constitution II; internal/investigation/backend/horizon.go). It is the incident
	// question's `fired_at`, which is what the harness runs an incident fixture at, and it is
	// **zero for a fixture that declares no incident question** — a 001 fixture or a bare
	// `worker record` is not an investigation and has no horizon to be honest about.
	Horizon time.Time
	// Shape is the published degradation shape the generator stamps onto the scenario:
	// `step` (the default), `slow-burn`, `distant-culprit`, `adjacent-decoy`. It comes from
	// `incident.world.shape`, because nothing about the shape of a degradation is readable out
	// of an event log — it is a property of the story the fixture tells.
	Shape string
	// OutputDir is where world/index.json is written.
	OutputDir string

	// EngineOnset is the onset search window the deterministic engine derives from the question
	// (algebra.OnsetSearchWindow). It is recorded for every pointer, in addition to the grid's own
	// per-pair onset windows, because onset is the first telemetry term the engine asks and an
	// unanswered onset makes the engine fall back to the alert instant — which then keys every
	// comparison after it to a reference instant no recording holds. Unset for a fixture with no
	// `incident:` block, which has no question to derive one from.
	EngineOnset *investigationv1.Window

	// Plan runs the deterministic engine over the world's own backend before the cross product is
	// taken, recording every term it issues. It is what makes a world a superset of the questions
	// the corpus will actually ask rather than a plausible guess at them (Phase 7 Track F).
	//
	// Nil for `worker record`, which has no fixture and therefore no engine to run.
	Plan worldEnginePass

	// Live runs the *live* engine — the production model configuration, real provider calls —
	// against the same taping backend, LivePasses times, and records every term it issues
	// (Phase 9 Track M).
	//
	// It exists because `Plan` covers only what the deterministic engine derives, and a live
	// investigator asks other questions: the first live evaluation of this corpus excluded 15 of
	// 16 fixtures on their miss rate for exactly that reason. The synthetic generator can answer
	// any in-algebra term, so the fix is to record what a live run asks rather than to widen the
	// admission bar.
	//
	// Nil for `--live-passes 0`, which is what keeps such a recording byte-identical.
	Live worldEnginePass
	// LivePasses is how many live runs Live makes, for the index's provenance.
	LivePasses int
	// ModelConfigDigest is the digest of the model configuration those passes ran under.
	ModelConfigDigest string
}

// worldEnginePass records every term one model-free engine run issues against the world's own
// generator. It returns how many distinct terms that was.
type worldEnginePass func(ctx context.Context, backend *synthetic.Backend, recorder sdk.Recorder) (*enginePassReport, error)

// enginePassReport is what the engine pass did, for the recording's own report.
type enginePassReport struct {
	// Terms is how many distinct terms the engine asked for.
	Terms int
	// Keys are those terms' recorded keys, so a live pass's contribution can be declared in the
	// index and carried forward by a later recording that runs no model at all.
	Keys []string
	// Handles are the drill-down handles its answers minted, so pass two follows them too.
	Handles []*investigationv1.Handle
	// Stop is the typed stop the run reached.
	Stop string
}

// worldReport is what a recording run did.
type worldReport struct {
	// Dir is the world directory.
	Dir string `json:"dir"`
	// Focus is the node the neighbourhood was taken around.
	Focus string `json:"focus"`
	// Nodes, Pointers and Edges are what the neighbourhood held.
	Nodes int `json:"nodes"`
	// Pointers is how many telemetry selectors the graph published for them.
	Pointers int `json:"pointers"`
	// Edges is how many edges the path set held.
	Edges int `json:"edges"`
	// Changes is how many changes the diff window held.
	Changes int `json:"changes"`
	// Terms is how many distinct algebra terms were recorded.
	Terms int `json:"terms"`
	// EngineTerms is how many of them the deterministic engine asked for itself, which is the
	// number that makes the world a superset of the investigation rather than a guess at it.
	EngineTerms int `json:"engine_terms"`
	// EngineStop is the typed stop that engine run reached.
	EngineStop string `json:"engine_stop,omitempty"`
	// LiveTerms is how many distinct terms the live passes of *this* recording asked for, and
	// CarriedLiveTerms how many earlier passes had already established and this one re-asked.
	LiveTerms        int `json:"live_terms,omitempty"`
	CarriedLiveTerms int `json:"carried_live_terms,omitempty"`
	// LivePasses is the cumulative pass count the index now declares.
	LivePasses int `json:"live_passes,omitempty"`
	// DrillDowns is how many of those came from depth-1 handles.
	DrillDowns int `json:"drill_downs"`
	// IndexDigest binds the index to the files it names.
	IndexDigest string `json:"index_digest"`
	// MissRate is zero for a fresh recording by construction: a recorder answers every term it
	// enumerates. It is published anyway, because the number a fixture is admitted on is the
	// one a *verification* run measures, and printing zero here is the reminder of that.
	MissRate float64 `json:"miss_rate"`
}

// recordWorld enumerates the cross product and writes the world.
func recordWorld(ctx context.Context, queryEngine *query.Engine, spec worldSpec) (*worldReport, error) {
	scenario, neighbourhood, err := buildScenario(ctx, queryEngine, spec)
	if err != nil {
		return nil, err
	}
	backend, err := synthetic.New(scenario)
	if err != nil {
		return nil, err
	}
	recorder, err := sdk.NewRecorderWithOptions(spec.OutputDir, sdk.RecordOptions{
		HopRadius:              uint32(spec.Hops), //nolint:gosec // a hop radius is a small positive integer
		DrillDownDepth:         1,
		WindowGrid:             spec.Grid,
		RedactionPolicyVersion: algebra.DefaultRedactionPolicyVersion,
		Focus:                  spec.Focus.String(),
	})
	if err != nil {
		return nil, err
	}

	report := &worldReport{
		Dir:      spec.OutputDir,
		Focus:    spec.Focus.String(),
		Nodes:    len(scenario.Entities),
		Edges:    len(scenario.Edges),
		Changes:  len(scenario.Changes),
		Pointers: len(neighbourhood.pointers),
	}

	handles := make([]*investigationv1.Handle, 0, 64)
	coverage := &sdk.LiveCoverage{}

	// Pass minus one: the live coverage an earlier recording established.
	//
	// A recorder deletes the answers its enumeration did not visit, which is what makes a
	// re-record byte-identical rather than a merge of two worlds. That rule would also delete
	// everything a live pass bought, so the live keys are declared in the index and re-asked
	// here, against the same deterministic generator, whether or not this run has a model. The
	// coverage therefore survives a `--live-passes 0` re-record without the recording ever
	// trusting a byte it did not produce itself.
	carried, carriedHandles, err := carryForwardLiveCoverage(ctx, backend, recorder, spec)
	if err != nil {
		return nil, err
	}
	if carried != nil {
		coverage.Passes = carried.Passes
		coverage.ModelConfigDigests = append(coverage.ModelConfigDigests, carried.ModelConfigDigests...)
		coverage.TermKeys = append(coverage.TermKeys, carried.TermKeys...)
		report.Terms += len(carried.TermKeys)
		report.CarriedLiveTerms = len(carried.TermKeys)
		handles = append(handles, carriedHandles...)
	}

	// Pass zero: the engine's own plan, recorded by construction.
	//
	// The cross product below is the *supplement* — it covers the questions a model may explore —
	// and this is the part that covers the questions the deterministic engine will certainly ask.
	// Enumerating only the cross product is what produced a world that intersected the engine's
	// own terms in nothing at all: the engine derives its onset search window and its comparison
	// pairs from the question, the grid derives its pairs from the manifest, and two derivations
	// of "the window" from different inputs do not meet. Running the engine here removes the
	// derivation from the recorder entirely — whatever it asks is what is recorded.
	if spec.Plan != nil {
		pass, err := spec.Plan(ctx, backend, recorder)
		if err != nil {
			return nil, err
		}
		report.Terms += pass.Terms
		report.EngineTerms = pass.Terms
		report.EngineStop = pass.Stop
		handles = append(handles, pass.Handles...)
	}

	// Pass zero and a half: what a *live* investigator asks.
	//
	// The deterministic plan is a lower bound on the questions an investigation puts. A model
	// chasing a hypothesis asks others — a different statistic on the same pointer, a pointer one
	// hop further out, a log pattern nobody derived — and a world that does not hold them answers
	// NOT_RECORDED, which is what excluded 15 of 16 fixtures from the first live evaluation. The
	// passes run the production configuration against this same generator, so every answer is the
	// generator's own and nothing about the recording depends on what the model happened to say.
	if spec.Live != nil {
		pass, err := spec.Live(ctx, backend, recorder)
		if err != nil {
			return nil, err
		}
		report.Terms += pass.Terms
		report.LiveTerms = pass.Terms
		handles = append(handles, pass.Handles...)
		coverage.Passes += uint32(spec.LivePasses) //nolint:gosec // a pass count is a small positive integer
		coverage.ModelConfigDigests = append(coverage.ModelConfigDigests, spec.ModelConfigDigest)
		coverage.TermKeys = append(coverage.TermKeys, pass.Keys...)
	}
	if declarer, ok := recorder.(sdk.LiveCoverageRecorder); ok && len(coverage.TermKeys) > 0 {
		declarer.DeclareLiveCoverage(coverage)
	}
	report.LivePasses = int(coverage.Passes)

	// Pass one: every telemetry term over the neighbourhood × the grid. The order is the order
	// of the sorted enumeration, so two runs over the same graph write the same bytes.
	for _, term := range enumerateTerms(neighbourhood, spec) {
		resp, err := recordOne(ctx, backend, recorder, spec.Horizon, term)
		if err != nil {
			return nil, err
		}
		report.Terms++
		handles = append(handles, handlesOf(resp)...)
	}

	// Pass two: the depth-1 drill-downs those answers minted, and the exemplars behind each
	// handle. A handle that cannot be presented back is decoration (research §10), so a world
	// that held the handles and not their answers would be a world that invites a miss.
	distinct, err := distinctHandles(handles)
	if err != nil {
		return nil, err
	}
	for _, handle := range distinct {
		for _, term := range []*algebra.Term{
			algebra.DrillDown(handle),
			algebra.Exemplars(handle, algebra.MaxExemplars),
		} {
			if _, err := recordOne(ctx, backend, recorder, spec.Horizon, term); err != nil {
				return nil, err
			}
			report.Terms++
			report.DrillDowns++
		}
	}

	digest, err := recorder.Close(ctx)
	if err != nil {
		return nil, err
	}
	report.IndexDigest = digest
	return report, nil
}

// recordOne executes one term and records the answer. A term the backend refuses is recorded
// too: a refusal is the answer to that question, and a world that omitted it would answer
// NOT_RECORDED to a question it has in fact already settled.
func recordOne(ctx context.Context, backend *synthetic.Backend, recorder sdk.Recorder,
	horizon time.Time, term *algebra.Term,
) (*algebra.Response, error) {
	req := &algebra.Request{
		Term:    term,
		ValidAt: nil,
		// The recording is keyed by the term, which already carries both instants where the
		// term has them. The request's own valid_at is the engine's framing of a call and is
		// deliberately not part of the key.
		//
		// `observed_at` is different, and it is carried: it is the investigation's horizon, and
		// past it there is no telemetry (constitution II; backend/horizon.go). The generator
		// clamps to it, so an enumerated window that ran past `fired_at` is recorded as the
		// window that was actually answerable — under the key the engine will ask for, because
		// the engine's own requests carry the same instant.
		DiscriminatingQuestion: "world_recording:cross_product",
	}
	if !horizon.IsZero() {
		req.ObservedAt = timestamppb.New(horizon.UTC())
	}
	clamped, _, state := algebra.ClampRequest(req)
	if state == algebra.PastHorizon {
		// A window lying entirely in the future is not a hole in the recording: the recorded
		// backend answers it from the horizon itself, without consulting the world.
		return backend.Execute(ctx, req)
	}
	resp, err := backend.Execute(ctx, clamped)
	if err != nil {
		return nil, fmt.Errorf("record %s: %w", algebra.TermName(term), err)
	}
	if err := recorder.Record(ctx, clamped, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

// carryForwardLiveCoverage re-asks the terms an earlier live pass filed into this world.
//
// The prior index is read directly rather than through LoadWorld when it declares no live
// coverage, so a world nobody ran a model against is not even opened and `worker record` behaves
// exactly as it did. When there *is* coverage the whole world is loaded and its digest checked,
// because a term carried forward out of a world that has drifted would carry a question nobody
// can account for.
func carryForwardLiveCoverage(
	ctx context.Context, backend *synthetic.Backend, recorder sdk.Recorder, spec worldSpec,
) (*sdk.LiveCoverage, []*investigationv1.Handle, error) {
	index, err := readWorldIndex(spec.OutputDir)
	if err != nil || index == nil || index.LiveCoverage == nil || len(index.LiveCoverage.TermKeys) == 0 {
		return nil, nil, err
	}
	world, err := sdk.LoadWorld(spec.OutputDir)
	if err != nil {
		return nil, nil, fmt.Errorf(
			"world %s declares live coverage but cannot be loaded, so the coverage cannot be carried forward: %w",
			spec.OutputDir, err)
	}
	handles := make([]*investigationv1.Handle, 0, 32)
	for _, key := range index.LiveCoverage.TermKeys {
		term, ok := world.Term(key)
		if !ok {
			return nil, nil, fmt.Errorf(
				"world %s declares live coverage of term %s, which it does not hold", spec.OutputDir, key)
		}
		answer, ok := world.Answer(key)
		if !ok {
			return nil, nil, fmt.Errorf(
				"world %s declares live coverage of term %s and holds no answer for it", spec.OutputDir, key)
		}
		// The recorded answer is re-filed verbatim rather than re-asked.
		//
		// Re-asking looks more honest and is in fact less so. A world is keyed by the
		// *canonicalised* term, and the term stored beside an answer is that canonical form —
		// so re-asking it is asking a question slightly different from the one a live
		// investigator actually put, and the generator is entitled to answer the two
		// differently. It did: a re-record then wrote a different digest under an unchanged key,
		// and the world stopped re-recording byte-identically.
		//
		// Re-filing is exactly what the coverage claims — "these answers were produced by this
		// generator for these keys" — and it cannot drift. The check that it has not gone stale
		// is the recorder's own: if any other pass of this same recording produces a *different*
		// answer under one of these keys, the recorder refuses the whole recording rather than
		// picking one, which is how a live coverage recorded against a graph that has since
		// changed makes itself known.
		if err := recorder.Record(ctx, &algebra.Request{
			Term:                   term,
			ObservedAt:             observedAt(spec.Horizon),
			DiscriminatingQuestion: "world_recording:live_coverage",
		}, answer); err != nil {
			return nil, nil, fmt.Errorf("carry forward live coverage of %s: %w", key, err)
		}
		handles = append(handles, handlesOf(answer)...)
	}
	return index.LiveCoverage, handles, nil
}

// observedAt is the horizon as a request timestamp, and nil for a recording that has none.
func observedAt(horizon time.Time) *timestamppb.Timestamp {
	if horizon.IsZero() {
		return nil
	}
	return timestamppb.New(horizon.UTC())
}

// readWorldIndex reads a world's index without checking it against its files. A directory with
// no index yet is not an error: it is the ordinary case of a first recording.
func readWorldIndex(dir string) (*sdk.WorldIndex, error) {
	raw, err := os.ReadFile(filepath.Join(dir, sdk.IndexFile)) //nolint:gosec // the path is the world being recorded
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", filepath.Join(dir, sdk.IndexFile), err)
	}
	index := &sdk.WorldIndex{}
	if err := json.Unmarshal(raw, index); err != nil {
		return nil, fmt.Errorf("parse %s: %w", filepath.Join(dir, sdk.IndexFile), err)
	}
	return index, nil
}

// neighbourhood is what the graph said about the focus: the nodes within the hop radius, the
// pointers on them, and the edges of the path set.
type neighbourhood struct {
	nodes    []*graphv1.NodeVersion
	pointers []pointerOn
	edges    []*graphv1.EdgeVersion
}

type pointerOn struct {
	entityID string
	pointer  *graphv1.Pointer
}

// buildScenario reads the graph and turns it into the generator's scenario plus the enumeration's
// neighbourhood. Nothing here is invented: the entities, their pointers, the edges and the
// changes all come from 001's published RPCs.
func buildScenario(ctx context.Context, queryEngine *query.Engine, spec worldSpec) (synthetic.Scenario, *neighbourhood, error) {
	var empty synthetic.Scenario

	subgraph, err := queryEngine.Subgraph(ctx, &graphv1.SubgraphRequest{
		Focus:     spec.Focus.Proto(),
		AsOf:      &graphv1.AsOf{ValidAt: timestamppb.New(spec.To)},
		Hops:      uint32(spec.Hops), //nolint:gosec // a hop radius is a small positive integer
		Direction: graphv1.Direction_BOTH,
	})
	if err != nil {
		return empty, nil, fmt.Errorf("subgraph around %s: %w", spec.Focus, err)
	}

	hood := &neighbourhood{edges: subgraph.GetEdges()}
	hood.nodes = append(hood.nodes, subgraph.GetFocus())
	hood.nodes = append(hood.nodes, subgraph.GetNodes()...)
	sort.SliceStable(hood.nodes, func(i, j int) bool { return hood.nodes[i].GetEntityId() < hood.nodes[j].GetEntityId() })
	sort.SliceStable(hood.edges, func(i, j int) bool {
		if hood.edges[i].GetSrcId() != hood.edges[j].GetSrcId() {
			return hood.edges[i].GetSrcId() < hood.edges[j].GetSrcId()
		}
		if hood.edges[i].GetDstId() != hood.edges[j].GetDstId() {
			return hood.edges[i].GetDstId() < hood.edges[j].GetDstId()
		}
		return hood.edges[i].GetType() < hood.edges[j].GetType()
	})

	// The shape is resolved before anything is read, so a manifest naming a shape this generator
	// does not publish fails the recording instead of recording a different fixture under the
	// same id.
	shapeName := spec.Shape
	if shapeName == "" {
		shapeName = synthetic.ShapeStep
	}
	shape, ok := synthetic.ShapeByName(shapeName)
	if !ok {
		return empty, nil, fmt.Errorf(
			"world shape %q is not published; want one of %s", shapeName, strings.Join(synthetic.ShapeNames(), ", "))
	}

	scenario := synthetic.Scenario{
		Seed:       spec.Seed,
		Start:      spec.From,
		End:        spec.To,
		Resolution: time.Minute,
	}
	seenEntity := make(map[string]struct{}, len(hood.nodes))
	for _, node := range hood.nodes {
		if node == nil || node.GetEntityId() == "" {
			continue
		}
		if _, dup := seenEntity[node.GetEntityId()]; dup {
			continue
		}
		seenEntity[node.GetEntityId()] = struct{}{}
		if node.GetType() == graphv1.NodeType_CHANGE {
			continue // a change is not a thing with telemetry; it is a thing that happened to one
		}

		entity := synthetic.Entity{
			EntityID:        node.GetEntityId(),
			Name:            displayNameOf(node),
			BaselineVersion: "baseline",
		}
		for _, pointer := range telemetryPointers(node) {
			entity.Selectors = append(entity.Selectors, pointer.GetSelector())
			hood.pointers = append(hood.pointers, pointerOn{entityID: node.GetEntityId(), pointer: pointer})
		}
		if len(entity.Selectors) == 0 {
			continue // a node the graph publishes no telemetry pointer for cannot be asked about
		}
		sort.Strings(entity.Selectors)
		scenario.Entities = append(scenario.Entities, entity)
	}
	sort.SliceStable(scenario.Entities, func(i, j int) bool {
		return scenario.Entities[i].EntityID < scenario.Entities[j].EntityID
	})
	sort.SliceStable(hood.pointers, func(i, j int) bool {
		if hood.pointers[i].entityID != hood.pointers[j].entityID {
			return hood.pointers[i].entityID < hood.pointers[j].entityID
		}
		return hood.pointers[i].pointer.GetSelector() < hood.pointers[j].pointer.GetSelector()
	})

	for _, edge := range hood.edges {
		scenario.Edges = append(scenario.Edges, synthetic.Edge{
			SrcEntityID: edge.GetSrcId(),
			DstEntityID: edge.GetDstId(),
			WeightClass: edge.GetWeightClass(),
		})
	}

	// The changes come from 001's Diff over the same window, with their targets and their valid
	// start. Which of them degrades is supplied on the command line and never inferred.
	diff, err := queryEngine.Diff(ctx, &graphv1.DiffRequest{
		Subgraph: &graphv1.SubgraphRequest{
			Focus:     spec.Focus.Proto(),
			Hops:      uint32(spec.Hops), //nolint:gosec // a hop radius is a small positive integer
			Direction: graphv1.Direction_BOTH,
		},
		T1: timestamppb.New(spec.From),
		T2: timestamppb.New(spec.To),
	})
	if err != nil {
		return empty, nil, fmt.Errorf("diff around %s: %w", spec.Focus, err)
	}
	culprits := make(map[string]struct{}, len(spec.Culprits))
	for _, id := range spec.Culprits {
		culprits[id] = struct{}{}
	}
	for _, ranked := range diff.GetChanges() {
		node := ranked.GetChange()
		scenario.Changes = append(scenario.Changes, synthetic.Change{
			EntityID:        node.GetEntityId(),
			At:              node.GetValid().GetStart().AsTime().UTC(),
			TargetEntityIDs: append([]string(nil), ranked.GetTargetEntityIds()...),
			Version:         versionOf(node),
			Degrades:        namesNode(culprits, node),
		})
	}
	sort.SliceStable(scenario.Changes, func(i, j int) bool {
		return scenario.Changes[i].EntityID < scenario.Changes[j].EntityID
	})

	// Last, so it stamps the changes the diff produced rather than a set that is still being
	// built, and so that `record-world` and the trajectory replay that reads the world it wrote
	// see the same series.
	shape.ApplyTo(&scenario)
	return scenario, hood, nil
}

// telemetryPointers keeps the pointer kinds a telemetry term can be asked about. A dashboard or
// a source link is a place for a person to look, not a selector a backend can execute.
func telemetryPointers(node *graphv1.NodeVersion) []*graphv1.Pointer {
	out := make([]*graphv1.Pointer, 0, len(node.GetPointers()))
	for _, pointer := range node.GetPointers() {
		switch pointer.GetKind() {
		case graphv1.PointerKind_METRIC, graphv1.PointerKind_LOG, graphv1.PointerKind_TRACE:
			if pointer.GetSelector() != "" {
				out = append(out, pointer)
			}
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].GetSelector() < out[j].GetSelector() })
	return out
}

func displayNameOf(node *graphv1.NodeVersion) string {
	if name := node.GetDisplayName(); name != "" {
		return name
	}
	if id := node.GetEntityId(); id != "" {
		return id
	}
	return "unknown"
}

// namesNode reports whether one of the supplied identifiers names this node — by its internal
// entity id, or by any of the refs a source used for it.
//
// Both spellings have to work. A human writes `k8s.change=shop/payments@rev7` in a manifest,
// because that is the identity the origin system uses; the graph stores an opaque entity id,
// because identity resolution may have merged several refs onto one entity. Matching on the
// entity id alone would silently never match a manifest, and a world whose culprit never
// degraded anything would look exactly like a world where the culprit was innocent.
func namesNode(identifiers map[string]struct{}, node *graphv1.NodeVersion) bool {
	if _, ok := identifiers[node.GetEntityId()]; ok {
		return true
	}
	for _, alias := range node.GetAliases() {
		if _, ok := identifiers[alias.GetNamespace()+"="+alias.GetValue()]; ok {
			return true
		}
	}
	return false
}

// versionOf reads the version a change rolled out: the suffix of the ref the origin system used
// for it, e.g. `rev7` from `k8s.change=shop/payments@rev7`. That suffix is the version tag the
// telemetry carries, which is what makes `errors_by_version` join a metric to a change.
//
// Where no ref says, the change's origin reference stands in, and where that is silent too the
// entity id does. Inventing a version string would put a fact in the telemetry that the graph
// does not hold.
func versionOf(node *graphv1.NodeVersion) string {
	for _, alias := range node.GetAliases() {
		value := alias.GetValue()
		if at := strings.LastIndex(value, "@"); at >= 0 && at+1 < len(value) {
			return value[at+1:]
		}
	}
	if change := node.GetChange(); change != nil {
		if ref := change.GetOriginRef(); ref != "" {
			return ref
		}
	}
	if name := node.GetDisplayName(); name != "" {
		return name
	}
	return node.GetEntityId()
}

// enumerateTerms is the cross product itself, in a fixed order.
func enumerateTerms(hood *neighbourhood, spec worldSpec) []*algebra.Term {
	terms := make([]*algebra.Term, 0, 256)

	for _, on := range hood.pointers {
		pointer := on.pointer
		for _, pair := range spec.Grid {
			for _, statistic := range recordedStatistics {
				terms = append(terms, algebra.Compare(pointer, pair, statistic))
			}
			window := pair.GetSymptom()
			baseline := pair.GetBaseline()

			terms = append(terms,
				algebra.MonitorState(pointer, window),
				algebra.NewLogPatterns(pointer, window, baseline),
			)
			if attribute := pointer.GetJoinKeys()["version"]; attribute != "" {
				terms = append(terms, algebra.ErrorsByVersion(pointer, window, attribute))
			}
			// The onset search window spans the whole pair, because onset is asked about when
			// the symptom began and the answer must be allowed to fall in the baseline.
			terms = append(terms, algebra.Onset(pointer,
				algebra.NewWindow(baseline.GetStart().AsTime(), window.GetEnd().AsTime()),
				investigationv1.OnsetMethod_SEASONAL_CUSUM))
		}
		// The engine's own onset search window, derived from the question by the same function
		// the engine calls (`algebra.OnsetSearchWindow`). It is asked of every pointer rather than
		// only the subject's, because the model may ask it of any of them and because a
		// re-ranking that moves the subject would otherwise leave the new subject's onset
		// unrecorded.
		if spec.EngineOnset != nil {
			terms = append(terms, algebra.Onset(pointer, spec.EngineOnset,
				investigationv1.OnsetMethod_SEASONAL_CUSUM))
		}
	}

	for _, edge := range hood.edges {
		for _, pair := range spec.Grid {
			terms = append(terms, algebra.ErrorSpans(
				edge.GetSrcId(), edge.GetDstId(), edge.GetType(), pair.GetSymptom()))
		}
	}
	return terms
}

func handlesOf(resp *algebra.Response) []*investigationv1.Handle {
	out := make([]*investigationv1.Handle, 0, 8)
	switch body := resp.GetDigest().GetBody().(type) {
	case *investigationv1.Digest_Metric:
		for _, series := range body.Metric.GetSeries() {
			if h := series.GetDrillDown().GetHandle(); h.GetValue() != "" {
				out = append(out, h)
			}
		}
	case *investigationv1.Digest_Log:
		for _, pattern := range body.Log.GetPatterns() {
			if h := pattern.GetDrillDown().GetHandle(); h.GetValue() != "" {
				out = append(out, h)
			}
		}
	case *investigationv1.Digest_Trace:
		for _, group := range body.Trace.GetGroups() {
			if h := group.GetDrillDown().GetHandle(); h.GetValue() != "" {
				out = append(out, h)
			}
		}
	case *investigationv1.Digest_ErrorsByVersion:
		for _, version := range body.ErrorsByVersion.GetVersions() {
			if h := version.GetDrillDown().GetHandle(); h.GetValue() != "" {
				out = append(out, h)
			}
		}
	}
	return out
}

// distinctHandles puts the minted handles into one total order and removes the duplicates, both
// by the handle's **whole canonical content** rather than by its `value` alone.
//
// A `Handle` is a value, the term key that minted it and a depth, and `drill_down` and
// `exemplars` are keyed on all three. The same drill-down target is routinely minted by two
// different parent terms — a compare the deterministic plan asked and a compare a live
// investigator asked reach the same series — and those are two handles, with two term keys, of
// which a world must hold both: whichever parent the engine asked, it presents back the handle
// *that* answer gave it, and a world holding only the other one answers NOT_RECORDED.
//
// Deduplicating on `value` alone held exactly one of them, and *which* one was decided by the
// order the passes happened to run in: the first live recording of a world kept the plan's
// handle, and a re-record — where the live coverage is re-asked first — kept the live one. Same
// term count, different keys, and therefore a world that did not re-record byte-identically.
func distinctHandles(handles []*investigationv1.Handle) ([]*investigationv1.Handle, error) {
	type keyed struct {
		key    string
		handle *investigationv1.Handle
	}
	seen := make(map[string]struct{}, len(handles))
	out := make([]keyed, 0, len(handles))
	for _, handle := range handles {
		encoded, err := graph.CanonicalJSON(handle)
		if err != nil {
			return nil, fmt.Errorf("canonicalise handle %q: %w", handle.GetValue(), err)
		}
		key := string(encoded)
		if _, dup := seen[key]; dup {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, keyed{key: key, handle: handle})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].key < out[j].key })
	distinct := make([]*investigationv1.Handle, 0, len(out))
	for _, each := range out {
		distinct = append(distinct, each.handle)
	}
	return distinct, nil
}

// parseWindowSpec reads `T1..T2` in RFC 3339.
func parseWindowSpec(spec string) (from, to time.Time, err error) {
	parts := strings.SplitN(spec, "..", 2)
	if len(parts) != 2 {
		return from, to, fmt.Errorf("--window %q is not T1..T2 in RFC 3339", spec)
	}
	from, err = time.Parse(time.RFC3339, strings.TrimSpace(parts[0]))
	if err != nil {
		return from, to, fmt.Errorf("--window start: %w", err)
	}
	to, err = time.Parse(time.RFC3339, strings.TrimSpace(parts[1]))
	if err != nil {
		return from, to, fmt.Errorf("--window end: %w", err)
	}
	if !to.After(from) {
		return from, to, fmt.Errorf("--window %q is empty or inverted", spec)
	}
	return from.UTC(), to.UTC(), nil
}

// parseGridSpec reads the window grid: either bare half-widths in seconds around a default
// reference instant, or explicit `<rfc3339>@<seconds>` entries. The grid is written into the
// index, so a reader of a world can see exactly which before/after pairs it holds.
func parseGridSpec(spec string, reference time.Time) ([]*investigationv1.WindowPair, error) {
	entries := splitCommas(spec)
	if len(entries) == 0 {
		return nil, fmt.Errorf("--grid is empty; a world with no window grid holds no comparisons")
	}
	pairs := make([]*investigationv1.WindowPair, 0, len(entries))
	for _, entry := range entries {
		at, widthText := splitGridEntry(entry, reference)
		if widthText == "" {
			return nil, fmt.Errorf("--grid entry %q has no half-width in seconds", entry)
		}
		seconds, err := strconv.Atoi(widthText)
		if err != nil || seconds <= 0 {
			return nil, fmt.Errorf("--grid entry %q: half-width must be a positive whole number of seconds", entry)
		}
		pairs = append(pairs, algebra.NewWindowPair(at, time.Duration(seconds)*time.Second))
	}
	sort.SliceStable(pairs, func(i, j int) bool {
		if !pairs[i].GetReferenceAt().AsTime().Equal(pairs[j].GetReferenceAt().AsTime()) {
			return pairs[i].GetReferenceAt().AsTime().Before(pairs[j].GetReferenceAt().AsTime())
		}
		return pairs[i].GetWidthSeconds() < pairs[j].GetWidthSeconds()
	})
	return pairs, nil
}

func splitGridEntry(entry string, reference time.Time) (time.Time, string) {
	at := strings.LastIndex(entry, "@")
	if at < 0 {
		return reference, strings.TrimSpace(entry)
	}
	parsed, err := time.Parse(time.RFC3339, strings.TrimSpace(entry[:at]))
	if err != nil {
		return reference, ""
	}
	return parsed.UTC(), strings.TrimSpace(entry[at+1:])
}

func splitCommas(spec string) []string {
	out := make([]string, 0, 4)
	for _, part := range strings.Split(spec, ",") {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func renderWorldReport(cmd *cobra.Command, global *globalOptions, report *worldReport) error {
	p := newPrinter(cmd.OutOrStdout(), global.Output)
	if p.json() {
		return p.writeJSON(report)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "recorded world %s\n", report.Dir)
	fmt.Fprintf(&b, "  focus            %s\n", report.Focus)
	fmt.Fprintf(&b, "  neighbourhood    %d nodes, %d pointers, %d edges, %d changes\n",
		report.Nodes, report.Pointers, report.Edges, report.Changes)
	fmt.Fprintf(&b, "  terms            %d (%d of them depth-1 drill-downs)\n", report.Terms, report.DrillDowns)
	if report.EngineTerms > 0 {
		fmt.Fprintf(&b, "  engine plan      %d term(s) the deterministic engine issued itself, stop %s\n",
			report.EngineTerms, report.EngineStop)
	}
	if report.LivePasses > 0 {
		fmt.Fprintf(&b, "  live coverage    %d pass(es) cumulative; %d term(s) this run, %d carried forward\n",
			report.LivePasses, report.LiveTerms, report.CarriedLiveTerms)
	}
	fmt.Fprintf(&b, "  index digest     %s\n", report.IndexDigest)
	fmt.Fprintf(&b, "  miss rate        %.6f (a fresh recording answers everything it enumerated; "+
		"the number that admits a fixture is the one a verification run measures)\n", report.MissRate)
	fmt.Fprintf(&b, "\n  provenance: synthetic — the telemetry was generated from this graph by\n"+
		"  pkg/backend/synthetic, a stand-in until feature 003's GCP backend records a real world.\n")
	return p.writeRaw(b.String())
}
