// SPDX-License-Identifier: Apache-2.0

// Public schema for the temporal system graph. Source of truth for events, entities and
// queries. Served via ConnectRPC (gRPC, gRPC-Web, JSON). Versioned with buf; breaking
// changes require a MAJOR bump and an event-log transformation (constitution IX).

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sreagent/graph/v1/graph.proto

package graphv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Pierre-Theophile/aisre/api/sreagent/graph/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngestServiceName is the fully-qualified name of the IngestService service.
	IngestServiceName = "sreagent.graph.v1.IngestService"
	// QueryServiceName is the fully-qualified name of the QueryService service.
	QueryServiceName = "sreagent.graph.v1.QueryService"
	// ResolutionServiceName is the fully-qualified name of the ResolutionService service.
	ResolutionServiceName = "sreagent.graph.v1.ResolutionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngestServiceIngestProcedure is the fully-qualified name of the IngestService's Ingest RPC.
	IngestServiceIngestProcedure = "/sreagent.graph.v1.IngestService/Ingest"
	// IngestServiceIngestBatchProcedure is the fully-qualified name of the IngestService's IngestBatch
	// RPC.
	IngestServiceIngestBatchProcedure = "/sreagent.graph.v1.IngestService/IngestBatch"
	// IngestServiceRegisterSourceProcedure is the fully-qualified name of the IngestService's
	// RegisterSource RPC.
	IngestServiceRegisterSourceProcedure = "/sreagent.graph.v1.IngestService/RegisterSource"
	// QueryServiceSubgraphProcedure is the fully-qualified name of the QueryService's Subgraph RPC.
	QueryServiceSubgraphProcedure = "/sreagent.graph.v1.QueryService/Subgraph"
	// QueryServiceDiffProcedure is the fully-qualified name of the QueryService's Diff RPC.
	QueryServiceDiffProcedure = "/sreagent.graph.v1.QueryService/Diff"
	// QueryServiceImpactProcedure is the fully-qualified name of the QueryService's Impact RPC.
	QueryServiceImpactProcedure = "/sreagent.graph.v1.QueryService/Impact"
	// QueryServicePointersProcedure is the fully-qualified name of the QueryService's Pointers RPC.
	QueryServicePointersProcedure = "/sreagent.graph.v1.QueryService/Pointers"
	// QueryServiceResolutionAuditProcedure is the fully-qualified name of the QueryService's
	// ResolutionAudit RPC.
	QueryServiceResolutionAuditProcedure = "/sreagent.graph.v1.QueryService/ResolutionAudit"
	// QueryServiceNodeHistoryProcedure is the fully-qualified name of the QueryService's NodeHistory
	// RPC.
	QueryServiceNodeHistoryProcedure = "/sreagent.graph.v1.QueryService/NodeHistory"
	// QueryServiceSuggestionsProcedure is the fully-qualified name of the QueryService's Suggestions
	// RPC.
	QueryServiceSuggestionsProcedure = "/sreagent.graph.v1.QueryService/Suggestions"
	// QueryServiceProposedDependenciesProcedure is the fully-qualified name of the QueryService's
	// ProposedDependencies RPC.
	QueryServiceProposedDependenciesProcedure = "/sreagent.graph.v1.QueryService/ProposedDependencies"
	// QueryServiceExtentProcedure is the fully-qualified name of the QueryService's Extent RPC.
	QueryServiceExtentProcedure = "/sreagent.graph.v1.QueryService/Extent"
	// ResolutionServiceConfirmProcedure is the fully-qualified name of the ResolutionService's Confirm
	// RPC.
	ResolutionServiceConfirmProcedure = "/sreagent.graph.v1.ResolutionService/Confirm"
	// ResolutionServiceRejectProcedure is the fully-qualified name of the ResolutionService's Reject
	// RPC.
	ResolutionServiceRejectProcedure = "/sreagent.graph.v1.ResolutionService/Reject"
	// ResolutionServiceSplitProcedure is the fully-qualified name of the ResolutionService's Split RPC.
	ResolutionServiceSplitProcedure = "/sreagent.graph.v1.ResolutionService/Split"
	// ResolutionServiceMergeProcedure is the fully-qualified name of the ResolutionService's Merge RPC.
	ResolutionServiceMergeProcedure = "/sreagent.graph.v1.ResolutionService/Merge"
	// ResolutionServiceConfirmDependencyProcedure is the fully-qualified name of the
	// ResolutionService's ConfirmDependency RPC.
	ResolutionServiceConfirmDependencyProcedure = "/sreagent.graph.v1.ResolutionService/ConfirmDependency"
	// ResolutionServiceRejectDependencyProcedure is the fully-qualified name of the ResolutionService's
	// RejectDependency RPC.
	ResolutionServiceRejectDependencyProcedure = "/sreagent.graph.v1.ResolutionService/RejectDependency"
)

// IngestServiceClient is a client for the sreagent.graph.v1.IngestService service.
type IngestServiceClient interface {
	Ingest(context.Context) *connect.BidiStreamForClient[v1.EventEnvelope, v1.IngestResult]
	IngestBatch(context.Context, *connect.Request[v1.IngestBatchRequest]) (*connect.Response[v1.IngestBatchResponse], error)
	RegisterSource(context.Context, *connect.Request[v1.RegisterSourceRequest]) (*connect.Response[v1.RegisterSourceResponse], error)
}

// NewIngestServiceClient constructs a client for the sreagent.graph.v1.IngestService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingestServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("IngestService").Methods()
	return &ingestServiceClient{
		ingest: connect.NewClient[v1.EventEnvelope, v1.IngestResult](
			httpClient,
			baseURL+IngestServiceIngestProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("Ingest")),
			connect.WithClientOptions(opts...),
		),
		ingestBatch: connect.NewClient[v1.IngestBatchRequest, v1.IngestBatchResponse](
			httpClient,
			baseURL+IngestServiceIngestBatchProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("IngestBatch")),
			connect.WithClientOptions(opts...),
		),
		registerSource: connect.NewClient[v1.RegisterSourceRequest, v1.RegisterSourceResponse](
			httpClient,
			baseURL+IngestServiceRegisterSourceProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("RegisterSource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingestServiceClient implements IngestServiceClient.
type ingestServiceClient struct {
	ingest         *connect.Client[v1.EventEnvelope, v1.IngestResult]
	ingestBatch    *connect.Client[v1.IngestBatchRequest, v1.IngestBatchResponse]
	registerSource *connect.Client[v1.RegisterSourceRequest, v1.RegisterSourceResponse]
}

// Ingest calls sreagent.graph.v1.IngestService.Ingest.
func (c *ingestServiceClient) Ingest(ctx context.Context) *connect.BidiStreamForClient[v1.EventEnvelope, v1.IngestResult] {
	return c.ingest.CallBidiStream(ctx)
}

// IngestBatch calls sreagent.graph.v1.IngestService.IngestBatch.
func (c *ingestServiceClient) IngestBatch(ctx context.Context, req *connect.Request[v1.IngestBatchRequest]) (*connect.Response[v1.IngestBatchResponse], error) {
	return c.ingestBatch.CallUnary(ctx, req)
}

// RegisterSource calls sreagent.graph.v1.IngestService.RegisterSource.
func (c *ingestServiceClient) RegisterSource(ctx context.Context, req *connect.Request[v1.RegisterSourceRequest]) (*connect.Response[v1.RegisterSourceResponse], error) {
	return c.registerSource.CallUnary(ctx, req)
}

// IngestServiceHandler is an implementation of the sreagent.graph.v1.IngestService service.
type IngestServiceHandler interface {
	Ingest(context.Context, *connect.BidiStream[v1.EventEnvelope, v1.IngestResult]) error
	IngestBatch(context.Context, *connect.Request[v1.IngestBatchRequest]) (*connect.Response[v1.IngestBatchResponse], error)
	RegisterSource(context.Context, *connect.Request[v1.RegisterSourceRequest]) (*connect.Response[v1.RegisterSourceResponse], error)
}

// NewIngestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngestServiceHandler(svc IngestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingestServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("IngestService").Methods()
	ingestServiceIngestHandler := connect.NewBidiStreamHandler(
		IngestServiceIngestProcedure,
		svc.Ingest,
		connect.WithSchema(ingestServiceMethods.ByName("Ingest")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceIngestBatchHandler := connect.NewUnaryHandler(
		IngestServiceIngestBatchProcedure,
		svc.IngestBatch,
		connect.WithSchema(ingestServiceMethods.ByName("IngestBatch")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceRegisterSourceHandler := connect.NewUnaryHandler(
		IngestServiceRegisterSourceProcedure,
		svc.RegisterSource,
		connect.WithSchema(ingestServiceMethods.ByName("RegisterSource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sreagent.graph.v1.IngestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngestServiceIngestProcedure:
			ingestServiceIngestHandler.ServeHTTP(w, r)
		case IngestServiceIngestBatchProcedure:
			ingestServiceIngestBatchHandler.ServeHTTP(w, r)
		case IngestServiceRegisterSourceProcedure:
			ingestServiceRegisterSourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngestServiceHandler struct{}

func (UnimplementedIngestServiceHandler) Ingest(context.Context, *connect.BidiStream[v1.EventEnvelope, v1.IngestResult]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.IngestService.Ingest is not implemented"))
}

func (UnimplementedIngestServiceHandler) IngestBatch(context.Context, *connect.Request[v1.IngestBatchRequest]) (*connect.Response[v1.IngestBatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.IngestService.IngestBatch is not implemented"))
}

func (UnimplementedIngestServiceHandler) RegisterSource(context.Context, *connect.Request[v1.RegisterSourceRequest]) (*connect.Response[v1.RegisterSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.IngestService.RegisterSource is not implemented"))
}

// QueryServiceClient is a client for the sreagent.graph.v1.QueryService service.
type QueryServiceClient interface {
	Subgraph(context.Context, *connect.Request[v1.SubgraphRequest]) (*connect.Response[v1.SubgraphResponse], error)
	Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error)
	Impact(context.Context, *connect.Request[v1.ImpactRequest]) (*connect.Response[v1.ImpactResponse], error)
	Pointers(context.Context, *connect.Request[v1.PointersRequest]) (*connect.Response[v1.PointersResponse], error)
	ResolutionAudit(context.Context, *connect.Request[v1.ResolutionAuditRequest]) (*connect.Response[v1.ResolutionAuditResponse], error)
	NodeHistory(context.Context, *connect.Request[v1.NodeHistoryRequest]) (*connect.Response[v1.NodeHistoryResponse], error)
	Suggestions(context.Context, *connect.Request[v1.SuggestionsRequest]) (*connect.Response[v1.SuggestionsResponse], error)
	// 003 plan item 2. The edge analogue of Suggestions: what a rule proposed and nobody has
	// decided, so a person can find it without reading the event log.
	ProposedDependencies(context.Context, *connect.Request[v1.ProposedDependenciesRequest]) (*connect.Response[v1.ProposedDependenciesResponse], error)
	// Return type is fully qualified: inside a service, the method name `Extent` shadows
	// the message name `Extent`, so the unqualified form does not resolve.
	Extent(context.Context, *connect.Request[v1.ExtentRequest]) (*connect.Response[v1.Extent], error)
}

// NewQueryServiceClient constructs a client for the sreagent.graph.v1.QueryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	queryServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("QueryService").Methods()
	return &queryServiceClient{
		subgraph: connect.NewClient[v1.SubgraphRequest, v1.SubgraphResponse](
			httpClient,
			baseURL+QueryServiceSubgraphProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Subgraph")),
			connect.WithClientOptions(opts...),
		),
		diff: connect.NewClient[v1.DiffRequest, v1.DiffResponse](
			httpClient,
			baseURL+QueryServiceDiffProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Diff")),
			connect.WithClientOptions(opts...),
		),
		impact: connect.NewClient[v1.ImpactRequest, v1.ImpactResponse](
			httpClient,
			baseURL+QueryServiceImpactProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Impact")),
			connect.WithClientOptions(opts...),
		),
		pointers: connect.NewClient[v1.PointersRequest, v1.PointersResponse](
			httpClient,
			baseURL+QueryServicePointersProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Pointers")),
			connect.WithClientOptions(opts...),
		),
		resolutionAudit: connect.NewClient[v1.ResolutionAuditRequest, v1.ResolutionAuditResponse](
			httpClient,
			baseURL+QueryServiceResolutionAuditProcedure,
			connect.WithSchema(queryServiceMethods.ByName("ResolutionAudit")),
			connect.WithClientOptions(opts...),
		),
		nodeHistory: connect.NewClient[v1.NodeHistoryRequest, v1.NodeHistoryResponse](
			httpClient,
			baseURL+QueryServiceNodeHistoryProcedure,
			connect.WithSchema(queryServiceMethods.ByName("NodeHistory")),
			connect.WithClientOptions(opts...),
		),
		suggestions: connect.NewClient[v1.SuggestionsRequest, v1.SuggestionsResponse](
			httpClient,
			baseURL+QueryServiceSuggestionsProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Suggestions")),
			connect.WithClientOptions(opts...),
		),
		proposedDependencies: connect.NewClient[v1.ProposedDependenciesRequest, v1.ProposedDependenciesResponse](
			httpClient,
			baseURL+QueryServiceProposedDependenciesProcedure,
			connect.WithSchema(queryServiceMethods.ByName("ProposedDependencies")),
			connect.WithClientOptions(opts...),
		),
		extent: connect.NewClient[v1.ExtentRequest, v1.Extent](
			httpClient,
			baseURL+QueryServiceExtentProcedure,
			connect.WithSchema(queryServiceMethods.ByName("Extent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// queryServiceClient implements QueryServiceClient.
type queryServiceClient struct {
	subgraph             *connect.Client[v1.SubgraphRequest, v1.SubgraphResponse]
	diff                 *connect.Client[v1.DiffRequest, v1.DiffResponse]
	impact               *connect.Client[v1.ImpactRequest, v1.ImpactResponse]
	pointers             *connect.Client[v1.PointersRequest, v1.PointersResponse]
	resolutionAudit      *connect.Client[v1.ResolutionAuditRequest, v1.ResolutionAuditResponse]
	nodeHistory          *connect.Client[v1.NodeHistoryRequest, v1.NodeHistoryResponse]
	suggestions          *connect.Client[v1.SuggestionsRequest, v1.SuggestionsResponse]
	proposedDependencies *connect.Client[v1.ProposedDependenciesRequest, v1.ProposedDependenciesResponse]
	extent               *connect.Client[v1.ExtentRequest, v1.Extent]
}

// Subgraph calls sreagent.graph.v1.QueryService.Subgraph.
func (c *queryServiceClient) Subgraph(ctx context.Context, req *connect.Request[v1.SubgraphRequest]) (*connect.Response[v1.SubgraphResponse], error) {
	return c.subgraph.CallUnary(ctx, req)
}

// Diff calls sreagent.graph.v1.QueryService.Diff.
func (c *queryServiceClient) Diff(ctx context.Context, req *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error) {
	return c.diff.CallUnary(ctx, req)
}

// Impact calls sreagent.graph.v1.QueryService.Impact.
func (c *queryServiceClient) Impact(ctx context.Context, req *connect.Request[v1.ImpactRequest]) (*connect.Response[v1.ImpactResponse], error) {
	return c.impact.CallUnary(ctx, req)
}

// Pointers calls sreagent.graph.v1.QueryService.Pointers.
func (c *queryServiceClient) Pointers(ctx context.Context, req *connect.Request[v1.PointersRequest]) (*connect.Response[v1.PointersResponse], error) {
	return c.pointers.CallUnary(ctx, req)
}

// ResolutionAudit calls sreagent.graph.v1.QueryService.ResolutionAudit.
func (c *queryServiceClient) ResolutionAudit(ctx context.Context, req *connect.Request[v1.ResolutionAuditRequest]) (*connect.Response[v1.ResolutionAuditResponse], error) {
	return c.resolutionAudit.CallUnary(ctx, req)
}

// NodeHistory calls sreagent.graph.v1.QueryService.NodeHistory.
func (c *queryServiceClient) NodeHistory(ctx context.Context, req *connect.Request[v1.NodeHistoryRequest]) (*connect.Response[v1.NodeHistoryResponse], error) {
	return c.nodeHistory.CallUnary(ctx, req)
}

// Suggestions calls sreagent.graph.v1.QueryService.Suggestions.
func (c *queryServiceClient) Suggestions(ctx context.Context, req *connect.Request[v1.SuggestionsRequest]) (*connect.Response[v1.SuggestionsResponse], error) {
	return c.suggestions.CallUnary(ctx, req)
}

// ProposedDependencies calls sreagent.graph.v1.QueryService.ProposedDependencies.
func (c *queryServiceClient) ProposedDependencies(ctx context.Context, req *connect.Request[v1.ProposedDependenciesRequest]) (*connect.Response[v1.ProposedDependenciesResponse], error) {
	return c.proposedDependencies.CallUnary(ctx, req)
}

// Extent calls sreagent.graph.v1.QueryService.Extent.
func (c *queryServiceClient) Extent(ctx context.Context, req *connect.Request[v1.ExtentRequest]) (*connect.Response[v1.Extent], error) {
	return c.extent.CallUnary(ctx, req)
}

// QueryServiceHandler is an implementation of the sreagent.graph.v1.QueryService service.
type QueryServiceHandler interface {
	Subgraph(context.Context, *connect.Request[v1.SubgraphRequest]) (*connect.Response[v1.SubgraphResponse], error)
	Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error)
	Impact(context.Context, *connect.Request[v1.ImpactRequest]) (*connect.Response[v1.ImpactResponse], error)
	Pointers(context.Context, *connect.Request[v1.PointersRequest]) (*connect.Response[v1.PointersResponse], error)
	ResolutionAudit(context.Context, *connect.Request[v1.ResolutionAuditRequest]) (*connect.Response[v1.ResolutionAuditResponse], error)
	NodeHistory(context.Context, *connect.Request[v1.NodeHistoryRequest]) (*connect.Response[v1.NodeHistoryResponse], error)
	Suggestions(context.Context, *connect.Request[v1.SuggestionsRequest]) (*connect.Response[v1.SuggestionsResponse], error)
	// 003 plan item 2. The edge analogue of Suggestions: what a rule proposed and nobody has
	// decided, so a person can find it without reading the event log.
	ProposedDependencies(context.Context, *connect.Request[v1.ProposedDependenciesRequest]) (*connect.Response[v1.ProposedDependenciesResponse], error)
	// Return type is fully qualified: inside a service, the method name `Extent` shadows
	// the message name `Extent`, so the unqualified form does not resolve.
	Extent(context.Context, *connect.Request[v1.ExtentRequest]) (*connect.Response[v1.Extent], error)
}

// NewQueryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueryServiceHandler(svc QueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queryServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("QueryService").Methods()
	queryServiceSubgraphHandler := connect.NewUnaryHandler(
		QueryServiceSubgraphProcedure,
		svc.Subgraph,
		connect.WithSchema(queryServiceMethods.ByName("Subgraph")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceDiffHandler := connect.NewUnaryHandler(
		QueryServiceDiffProcedure,
		svc.Diff,
		connect.WithSchema(queryServiceMethods.ByName("Diff")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceImpactHandler := connect.NewUnaryHandler(
		QueryServiceImpactProcedure,
		svc.Impact,
		connect.WithSchema(queryServiceMethods.ByName("Impact")),
		connect.WithHandlerOptions(opts...),
	)
	queryServicePointersHandler := connect.NewUnaryHandler(
		QueryServicePointersProcedure,
		svc.Pointers,
		connect.WithSchema(queryServiceMethods.ByName("Pointers")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceResolutionAuditHandler := connect.NewUnaryHandler(
		QueryServiceResolutionAuditProcedure,
		svc.ResolutionAudit,
		connect.WithSchema(queryServiceMethods.ByName("ResolutionAudit")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceNodeHistoryHandler := connect.NewUnaryHandler(
		QueryServiceNodeHistoryProcedure,
		svc.NodeHistory,
		connect.WithSchema(queryServiceMethods.ByName("NodeHistory")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceSuggestionsHandler := connect.NewUnaryHandler(
		QueryServiceSuggestionsProcedure,
		svc.Suggestions,
		connect.WithSchema(queryServiceMethods.ByName("Suggestions")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceProposedDependenciesHandler := connect.NewUnaryHandler(
		QueryServiceProposedDependenciesProcedure,
		svc.ProposedDependencies,
		connect.WithSchema(queryServiceMethods.ByName("ProposedDependencies")),
		connect.WithHandlerOptions(opts...),
	)
	queryServiceExtentHandler := connect.NewUnaryHandler(
		QueryServiceExtentProcedure,
		svc.Extent,
		connect.WithSchema(queryServiceMethods.ByName("Extent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sreagent.graph.v1.QueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueryServiceSubgraphProcedure:
			queryServiceSubgraphHandler.ServeHTTP(w, r)
		case QueryServiceDiffProcedure:
			queryServiceDiffHandler.ServeHTTP(w, r)
		case QueryServiceImpactProcedure:
			queryServiceImpactHandler.ServeHTTP(w, r)
		case QueryServicePointersProcedure:
			queryServicePointersHandler.ServeHTTP(w, r)
		case QueryServiceResolutionAuditProcedure:
			queryServiceResolutionAuditHandler.ServeHTTP(w, r)
		case QueryServiceNodeHistoryProcedure:
			queryServiceNodeHistoryHandler.ServeHTTP(w, r)
		case QueryServiceSuggestionsProcedure:
			queryServiceSuggestionsHandler.ServeHTTP(w, r)
		case QueryServiceProposedDependenciesProcedure:
			queryServiceProposedDependenciesHandler.ServeHTTP(w, r)
		case QueryServiceExtentProcedure:
			queryServiceExtentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQueryServiceHandler struct{}

func (UnimplementedQueryServiceHandler) Subgraph(context.Context, *connect.Request[v1.SubgraphRequest]) (*connect.Response[v1.SubgraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Subgraph is not implemented"))
}

func (UnimplementedQueryServiceHandler) Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Diff is not implemented"))
}

func (UnimplementedQueryServiceHandler) Impact(context.Context, *connect.Request[v1.ImpactRequest]) (*connect.Response[v1.ImpactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Impact is not implemented"))
}

func (UnimplementedQueryServiceHandler) Pointers(context.Context, *connect.Request[v1.PointersRequest]) (*connect.Response[v1.PointersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Pointers is not implemented"))
}

func (UnimplementedQueryServiceHandler) ResolutionAudit(context.Context, *connect.Request[v1.ResolutionAuditRequest]) (*connect.Response[v1.ResolutionAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.ResolutionAudit is not implemented"))
}

func (UnimplementedQueryServiceHandler) NodeHistory(context.Context, *connect.Request[v1.NodeHistoryRequest]) (*connect.Response[v1.NodeHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.NodeHistory is not implemented"))
}

func (UnimplementedQueryServiceHandler) Suggestions(context.Context, *connect.Request[v1.SuggestionsRequest]) (*connect.Response[v1.SuggestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Suggestions is not implemented"))
}

func (UnimplementedQueryServiceHandler) ProposedDependencies(context.Context, *connect.Request[v1.ProposedDependenciesRequest]) (*connect.Response[v1.ProposedDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.ProposedDependencies is not implemented"))
}

func (UnimplementedQueryServiceHandler) Extent(context.Context, *connect.Request[v1.ExtentRequest]) (*connect.Response[v1.Extent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.QueryService.Extent is not implemented"))
}

// ResolutionServiceClient is a client for the sreagent.graph.v1.ResolutionService service.
type ResolutionServiceClient interface {
	Confirm(context.Context, *connect.Request[v1.ConfirmMerge]) (*connect.Response[v1.IngestResult], error)
	Reject(context.Context, *connect.Request[v1.RejectMerge]) (*connect.Response[v1.IngestResult], error)
	Split(context.Context, *connect.Request[v1.SplitEntity]) (*connect.Response[v1.IngestResult], error)
	Merge(context.Context, *connect.Request[v1.ManualMerge]) (*connect.Response[v1.IngestResult], error)
	// 003 plan item 2. Separate methods rather than overloads of Confirm/Reject, because the
	// decisions are about different things: Confirm says two refs are one entity, ConfirmDependency
	// says an edge exists between two entities that are not.
	//
	// Request types are fully qualified for the same reason `Extent` above is: inside a service the
	// method name shadows the message name of the same spelling, so the unqualified form does not
	// resolve.
	ConfirmDependency(context.Context, *connect.Request[v1.ConfirmDependency]) (*connect.Response[v1.IngestResult], error)
	RejectDependency(context.Context, *connect.Request[v1.RejectDependency]) (*connect.Response[v1.IngestResult], error)
}

// NewResolutionServiceClient constructs a client for the sreagent.graph.v1.ResolutionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResolutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResolutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resolutionServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("ResolutionService").Methods()
	return &resolutionServiceClient{
		confirm: connect.NewClient[v1.ConfirmMerge, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceConfirmProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("Confirm")),
			connect.WithClientOptions(opts...),
		),
		reject: connect.NewClient[v1.RejectMerge, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceRejectProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("Reject")),
			connect.WithClientOptions(opts...),
		),
		split: connect.NewClient[v1.SplitEntity, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceSplitProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("Split")),
			connect.WithClientOptions(opts...),
		),
		merge: connect.NewClient[v1.ManualMerge, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceMergeProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("Merge")),
			connect.WithClientOptions(opts...),
		),
		confirmDependency: connect.NewClient[v1.ConfirmDependency, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceConfirmDependencyProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("ConfirmDependency")),
			connect.WithClientOptions(opts...),
		),
		rejectDependency: connect.NewClient[v1.RejectDependency, v1.IngestResult](
			httpClient,
			baseURL+ResolutionServiceRejectDependencyProcedure,
			connect.WithSchema(resolutionServiceMethods.ByName("RejectDependency")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resolutionServiceClient implements ResolutionServiceClient.
type resolutionServiceClient struct {
	confirm           *connect.Client[v1.ConfirmMerge, v1.IngestResult]
	reject            *connect.Client[v1.RejectMerge, v1.IngestResult]
	split             *connect.Client[v1.SplitEntity, v1.IngestResult]
	merge             *connect.Client[v1.ManualMerge, v1.IngestResult]
	confirmDependency *connect.Client[v1.ConfirmDependency, v1.IngestResult]
	rejectDependency  *connect.Client[v1.RejectDependency, v1.IngestResult]
}

// Confirm calls sreagent.graph.v1.ResolutionService.Confirm.
func (c *resolutionServiceClient) Confirm(ctx context.Context, req *connect.Request[v1.ConfirmMerge]) (*connect.Response[v1.IngestResult], error) {
	return c.confirm.CallUnary(ctx, req)
}

// Reject calls sreagent.graph.v1.ResolutionService.Reject.
func (c *resolutionServiceClient) Reject(ctx context.Context, req *connect.Request[v1.RejectMerge]) (*connect.Response[v1.IngestResult], error) {
	return c.reject.CallUnary(ctx, req)
}

// Split calls sreagent.graph.v1.ResolutionService.Split.
func (c *resolutionServiceClient) Split(ctx context.Context, req *connect.Request[v1.SplitEntity]) (*connect.Response[v1.IngestResult], error) {
	return c.split.CallUnary(ctx, req)
}

// Merge calls sreagent.graph.v1.ResolutionService.Merge.
func (c *resolutionServiceClient) Merge(ctx context.Context, req *connect.Request[v1.ManualMerge]) (*connect.Response[v1.IngestResult], error) {
	return c.merge.CallUnary(ctx, req)
}

// ConfirmDependency calls sreagent.graph.v1.ResolutionService.ConfirmDependency.
func (c *resolutionServiceClient) ConfirmDependency(ctx context.Context, req *connect.Request[v1.ConfirmDependency]) (*connect.Response[v1.IngestResult], error) {
	return c.confirmDependency.CallUnary(ctx, req)
}

// RejectDependency calls sreagent.graph.v1.ResolutionService.RejectDependency.
func (c *resolutionServiceClient) RejectDependency(ctx context.Context, req *connect.Request[v1.RejectDependency]) (*connect.Response[v1.IngestResult], error) {
	return c.rejectDependency.CallUnary(ctx, req)
}

// ResolutionServiceHandler is an implementation of the sreagent.graph.v1.ResolutionService service.
type ResolutionServiceHandler interface {
	Confirm(context.Context, *connect.Request[v1.ConfirmMerge]) (*connect.Response[v1.IngestResult], error)
	Reject(context.Context, *connect.Request[v1.RejectMerge]) (*connect.Response[v1.IngestResult], error)
	Split(context.Context, *connect.Request[v1.SplitEntity]) (*connect.Response[v1.IngestResult], error)
	Merge(context.Context, *connect.Request[v1.ManualMerge]) (*connect.Response[v1.IngestResult], error)
	// 003 plan item 2. Separate methods rather than overloads of Confirm/Reject, because the
	// decisions are about different things: Confirm says two refs are one entity, ConfirmDependency
	// says an edge exists between two entities that are not.
	//
	// Request types are fully qualified for the same reason `Extent` above is: inside a service the
	// method name shadows the message name of the same spelling, so the unqualified form does not
	// resolve.
	ConfirmDependency(context.Context, *connect.Request[v1.ConfirmDependency]) (*connect.Response[v1.IngestResult], error)
	RejectDependency(context.Context, *connect.Request[v1.RejectDependency]) (*connect.Response[v1.IngestResult], error)
}

// NewResolutionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResolutionServiceHandler(svc ResolutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resolutionServiceMethods := v1.File_sreagent_graph_v1_graph_proto.Services().ByName("ResolutionService").Methods()
	resolutionServiceConfirmHandler := connect.NewUnaryHandler(
		ResolutionServiceConfirmProcedure,
		svc.Confirm,
		connect.WithSchema(resolutionServiceMethods.ByName("Confirm")),
		connect.WithHandlerOptions(opts...),
	)
	resolutionServiceRejectHandler := connect.NewUnaryHandler(
		ResolutionServiceRejectProcedure,
		svc.Reject,
		connect.WithSchema(resolutionServiceMethods.ByName("Reject")),
		connect.WithHandlerOptions(opts...),
	)
	resolutionServiceSplitHandler := connect.NewUnaryHandler(
		ResolutionServiceSplitProcedure,
		svc.Split,
		connect.WithSchema(resolutionServiceMethods.ByName("Split")),
		connect.WithHandlerOptions(opts...),
	)
	resolutionServiceMergeHandler := connect.NewUnaryHandler(
		ResolutionServiceMergeProcedure,
		svc.Merge,
		connect.WithSchema(resolutionServiceMethods.ByName("Merge")),
		connect.WithHandlerOptions(opts...),
	)
	resolutionServiceConfirmDependencyHandler := connect.NewUnaryHandler(
		ResolutionServiceConfirmDependencyProcedure,
		svc.ConfirmDependency,
		connect.WithSchema(resolutionServiceMethods.ByName("ConfirmDependency")),
		connect.WithHandlerOptions(opts...),
	)
	resolutionServiceRejectDependencyHandler := connect.NewUnaryHandler(
		ResolutionServiceRejectDependencyProcedure,
		svc.RejectDependency,
		connect.WithSchema(resolutionServiceMethods.ByName("RejectDependency")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sreagent.graph.v1.ResolutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResolutionServiceConfirmProcedure:
			resolutionServiceConfirmHandler.ServeHTTP(w, r)
		case ResolutionServiceRejectProcedure:
			resolutionServiceRejectHandler.ServeHTTP(w, r)
		case ResolutionServiceSplitProcedure:
			resolutionServiceSplitHandler.ServeHTTP(w, r)
		case ResolutionServiceMergeProcedure:
			resolutionServiceMergeHandler.ServeHTTP(w, r)
		case ResolutionServiceConfirmDependencyProcedure:
			resolutionServiceConfirmDependencyHandler.ServeHTTP(w, r)
		case ResolutionServiceRejectDependencyProcedure:
			resolutionServiceRejectDependencyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResolutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResolutionServiceHandler struct{}

func (UnimplementedResolutionServiceHandler) Confirm(context.Context, *connect.Request[v1.ConfirmMerge]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.Confirm is not implemented"))
}

func (UnimplementedResolutionServiceHandler) Reject(context.Context, *connect.Request[v1.RejectMerge]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.Reject is not implemented"))
}

func (UnimplementedResolutionServiceHandler) Split(context.Context, *connect.Request[v1.SplitEntity]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.Split is not implemented"))
}

func (UnimplementedResolutionServiceHandler) Merge(context.Context, *connect.Request[v1.ManualMerge]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.Merge is not implemented"))
}

func (UnimplementedResolutionServiceHandler) ConfirmDependency(context.Context, *connect.Request[v1.ConfirmDependency]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.ConfirmDependency is not implemented"))
}

func (UnimplementedResolutionServiceHandler) RejectDependency(context.Context, *connect.Request[v1.RejectDependency]) (*connect.Response[v1.IngestResult], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sreagent.graph.v1.ResolutionService.RejectDependency is not implemented"))
}
